/* ============================================================
   ArchWander — Seoul Location Data
   47 locations
   Edit this file to add / modify Seoul locations.
   ============================================================ */

const LOCS_SEOUL = [
  {
    id:'dongdaemun-design-plaza',
    name:'Dongdaemun Design Plaza (DDP)',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Parametric Design',
    era:'2000–Present', city:'seoul',
    arch:'Zaha Hadid Architects', archs:['Zaha Hadid Architects'],
    yr:2014, access:'Free Admission', style:'Neo-Futurism',
    lat:37.5669, lng:127.0094,
    addr:'281 Euljiro, Jung-gu, Seoul', hood:'Dongdaemun',
    desc:'A landmark of parametric architecture by Zaha Hadid, the DDP is a vast steel-and-aluminium blob rising from the historic Dongdaemun site. Completed in 2014 on the footprint of a Joseon-era fortress wall, it houses multiple galleries, a design museum, and a 24-hour design market beneath its undulating 85,320 m² skin. The building sits atop excavated archaeological remains that are displayed in situ at the History and Culture Park surrounding it.',
    hours:'Tue–Sun 10:00 AM – 8:00 PM (galleries) · Design Market 24 hrs',
    lastEntry:'7:00 PM',
    admission:'Outdoor & design market: Free · Special exhibitions vary',
    tourOk:true, tourInfo:'Guided tours available on weekends. Audio guide available in Korean, English, and Japanese.',
    web:'https://www.ddp.or.kr/eng',
    transit:'2 4 5 → Dongdaemun History & Culture Park (Exit 1)',
    walkFrom:'Cheonggyecheon: 5 min · Gwangjang Market: 8 min',
    gmaps:'https://maps.google.com/?q=Dongdaemun+Design+Plaza+Seoul',
    archdaily:'https://www.archdaily.com/tag/ddp',
    wiki:'https://en.wikipedia.org/wiki/Dongdaemun_Design_Plaza',
    tags:['Zaha Hadid','Neo-Futurism','Parametric','Design Museum','Landmark','Free'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Dongdaemun_Design_Plaza_%28DDP%29.jpg/800px-Dongdaemun_Design_Plaza_%28DDP%29.jpg'
    ],
    drawings:[]
  },
  {
    id:'seoul-city-hall',
    name:'Seoul City Hall (New)',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'iARC Architects (Yoo-Hyun Rhee)', archs:['iARC Architects'],
    yr:2012, access:'Free Admission', style:'Contemporary',
    lat:37.566736, lng:126.9784892,
    addr:'110 Sejong-daero, Jung-gu, Seoul', hood:'Gwanghwamun / City Hall',
    desc:'The new Seoul City Hall, completed in 2012, is a dramatic glass wave that appears to crash against — yet protects — the original 1926 Japanese colonial-era City Hall behind it. Designed by Yoo-Hyun Rhee of iARC Architects following an open competition, the building\'s facade is composed of 7,366 panes of glass and functions as an ecological filter, reducing energy consumption. Inside, the nine-story atrium hosts a vertical garden of 65,000 plants — the largest indoor green wall in the world.',
    hours:'Mon–Fri 9:00 AM – 6:00 PM (public areas) · Lobby and garden: free',
    lastEntry:'5:30 PM',
    admission:'Free',
    tourOk:true, tourInfo:'Self-guided access to the lobby and vertical garden. Guided civic tours available on select days.',
    web:'https://english.seoul.go.kr',
    transit:'1 2 → City Hall (Exit 4 or 5)',
    walkFrom:'Cheonggyecheon: 4 min · Deoksugung Palace: 3 min · Gwanghwamun Square: 8 min',
    gmaps:'https://maps.google.com/?q=Seoul+New+City+Hall',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Seoul_Metropolitan_Government',
    tags:['iARC','Contemporary','Glass','Vertical Garden','Civic','Free'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Seoul_City_Hall_20130608_142638.jpg/800px-Seoul_City_Hall_20130608_142638.jpg'
    ],
    drawings:[]
  },
  {
    id:'lotte-world-tower',
    name:'Lotte World Tower',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'KPF (Kohn Pedersen Fox)', archs:['KPF (Kohn Pedersen Fox)'],
    yr:2017, access:'Paid Ticket', style:'Contemporary Supertall',
    lat:37.5125, lng:127.1025,
    addr:'300 Olympic-ro, Songpa-gu, Seoul', hood:'Jamsil',
    desc:'At 555 metres and 123 floors, Lotte World Tower is the fifth-tallest building in the world and the tallest in South Korea. Designed by KPF and completed in 2017, the tower\'s slender profile draws on traditional Korean celadon ceramics and calligraphic brushstrokes — the silhouette tapers dramatically from a wide base to a crystalline glass pinnacle. It contains a luxury hotel, residences, offices, a cultural complex, the Seoul Sky observatory (floors 117–123), and the world\'s highest glass-floor observation deck.',
    hours:'Seoul Sky: Daily 9:30 AM – 11:00 PM',
    lastEntry:'10:00 PM',
    admission:'Seoul Sky: from ₩27,000 · Express pass available',
    tourOk:true, tourInfo:'Self-guided observatory access. The tower complex includes Lotte World Mall for shopping and dining.',
    web:'https://www.lwt.co.kr/eng',
    transit:'2 8 → Jamsil (Exit 1 or 2)',
    walkFrom:'Lotte World Mall: direct connection · Seokchon Lake: 8 min',
    gmaps:'https://maps.google.com/?q=Lotte+World+Tower+Seoul',
    archdaily:'https://www.archdaily.com/884627/lotte-world-tower-kohn-pedersen-fox',
    wiki:'https://en.wikipedia.org/wiki/Lotte_World_Tower',
    tags:['KPF','Supertall','Observatory','Jamsil','Skyscraper','555m'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Lotte_World_Tower_Panorama_from_Seokchon_Lake_%28cropped%29.jpg/800px-Lotte_World_Tower_Panorama_from_Seokchon_Lake_%28cropped%29.jpg'
    ],
    drawings:[]
  },
  {
    id:'mmca-seoul',
    name:'MMCA Seoul (국립현대미술관 서울관)',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Hyun-Jun Mihn / mp_art architects', archs:['Hyun-Jun Mihn / mp_art architects'],
    yr:2013, access:'Paid Ticket', style:'Contemporary',
    lat:37.5788, lng:126.9803,
    addr:'30 Samcheong-ro, Jongno-gu, Seoul', hood:'Samcheong-dong / Gyeongbokgung',
    desc:'The Seoul branch of the National Museum of Modern and Contemporary Art opened in 2013, occupying a site historically used as military facilities within the Gyeongbokgung palace precinct. Designed by Hyun-Jun Mihn of mp_art architects, the museum weaves new volumes through pre-existing structures — reusing a military police building, a generator plant, and historic walls — creating a layered sequence of courtyards and gallery halls grounded in the Korean concept of "madang" (communal yard).',
    hours:'Tue–Sun 10:00 AM – 6:00 PM · Fri–Sat until 9:00 PM',
    lastEntry:'1 hr before closing',
    admission:'Permanent collection: Free · Special exhibitions: from ₩4,000',
    tourOk:true, tourInfo:'Docent tours available Tue–Sun. Audio guide in Korean and English.',
    web:'https://www.mmca.go.kr/eng',
    transit:'3 → Anguk (Exit 1, 10-min walk)',
    walkFrom:'Gyeongbokgung: 8 min · Bukchon: 12 min · Insadong: 15 min',
    gmaps:'https://maps.google.com/?q=MMCA+Seoul+National+Museum+Modern+Contemporary+Art',
    archdaily:'https://www.archdaily.com/775738/museum-of-modern-and-contemporary-art-mp-art-architects-plus-siaplan-consortium',
    wiki:'https://en.wikipedia.org/wiki/National_Museum_of_Modern_and_Contemporary_Art',
    tags:['mp_art architects','Contemporary','Free','Museum','Samcheong','Jongno'],
    photos:[],
    drawings:[]
  },
  {
    id:'ewha-campus-complex',
    name:'Ewha Womans University Campus Complex',
    cat:'Universities & Research', cc:'c-uni', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Dominique Perrault Architecture', archs:['Dominique Perrault Architecture'],
    yr:2008, access:'Free Admission', style:'Contemporary / Landscape Architecture',
    lat:37.5619, lng:126.9468,
    addr:'52 Ewhayeodae-gil, Seodaemun-gu, Seoul', hood:'Sinchon / Ewha',
    desc:'Dominique Perrault\'s 2008 Campus Center for Ewha Womans University is a radical act of subtraction: a 6-storey academic complex carved into the hillside, opening a 250-metre valley through the heart of the campus. Rather than a freestanding building, Perrault created a sunken canyon flanked by two glass-faced slabs that dissolve into landscaped terraces above. The result is a public green space — freely accessible to all — that also contains six floors of library, auditorium, cafeteria, and sports facilities.',
    hours:'Campus open daily · Interior during academic calendar (Mon–Fri 9:00 AM – 10:00 PM)',
    lastEntry:'',
    admission:'Free (campus & valley)',
    tourOk:true, tourInfo:'Self-guided access to the campus valley. Interiors accessible on academic calendar.',
    web:'https://www.ewha.ac.kr/ewhaen/',
    transit:'2 → Ewha Womans University (Exit 2, 5-min walk)',
    walkFrom:'Sinchon Station: 10 min · Yonsei University: 15 min',
    gmaps:'https://maps.google.com/?q=Ewha+Womans+University+Campus+Complex',
    archdaily:'https://www.archdaily.com/tag/ewha-campus-center',
    wiki:'https://en.wikipedia.org/wiki/Ewha_Womans_University',
    tags:['Dominique Perrault','University','Landscape','Free','Sinchon','Iconic'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/ECC_Ewha_Womans_University.jpg/800px-ECC_Ewha_Womans_University.jpg'
    ],
    drawings:[]
  },
  {
    id:'dayangsanghoi',
    name:'Dayangsanghoi',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'TUNEplanning', archs:['TUNEplanning'],
    yr:2013, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.6127, lng:126.965,
    addr:'Pyeongchang-dong, Jongno-gu, Seoul', hood:'Pyeongchang-dong',
    desc:'A compact multi-programme lounge bar and creative space by TUNEplanning, completed in 2013 in the quiet residential enclave of Pyeongchang-dong at the foot of Bukhansan mountain. The 84 m² project layers exhibition space, a private lounge, studio, and restaurant within a raw, material-honest interior that references the neighbourhood\'s cultured, understated character. The building has appeared widely in architecture media as an example of Seoul\'s small-scale contemporary design culture.',
    hours:'Varies by programming',
    lastEntry:'',
    admission:'Varies',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'3 → Gyeongbokgung (Exit 3) + Bus 7022 toward Pyeongchang-dong',
    walkFrom:'Bukhansan entrance: 20 min',
    gmaps:'https://maps.google.com/?q=Pyeongchang-dong+Jongno+Seoul',
    archdaily:'https://www.archdaily.com/785045/dayangsanghoi-tuneplanning',
    wiki:'',
    tags:['TUNEplanning','Small Scale','Pyeongchang-dong','Bukhansan','Creative Space'],
    photos:[],
    drawings:[]
  },
  {
    id:'saemoonan-church',
    name:'Saemoonan Church',
    cat:'Religious Architecture', cc:'c-rel', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Seoinn Design Group + Lee Eunseok', archs:['Seoinn Design Group'],
    yr:2019, access:'Free Admission', style:'Contemporary / Sacred',
    lat:37.5706967, lng:126.9735593,
    addr:'97 Saemunan-ro, Jongno-gu, Seoul', hood:'Gwanghwamun',
    desc:'Saemoonan Church, founded in 1887 as Korea\'s first Protestant congregation, received a dramatically new home in 2019 designed by Dongkyu Choi (Seoinn Design Group) and Eunseok Lee. Rather than a closed sanctuary, the 13-storey building opens a generous civic courtyard to Saemunan-ro, dissolving the boundary between sacred and urban space. A hollow front facade and bent arch gate frame the plaza, while a floating cross of translucent concrete becomes the tower\'s modern spire — visible from across Gwanghwamun.',
    hours:'Mon–Sat 9:00 AM – 5:00 PM · Sun services: 9 AM, 11 AM, 2 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'Visitors welcome outside service hours. The courtyard and exterior are freely accessible.',
    web:'https://www.saemoonan.org',
    transit:'5 → Gwanghwamun (Exit 7) · 3 → Gyeongbokgung (Exit 8)',
    walkFrom:'Gwanghwamun Square: 6 min · Gyeongbokgung: 8 min',
    gmaps:'https://maps.google.com/?q=Saemoonan+Church+Seoul',
    archdaily:'https://www.archdaily.com/923823/saemoonan-church-seoinn-design-group-plus-lee-eunseok',
    wiki:'https://en.wikipedia.org/wiki/Saemoonan_Church',
    tags:['Seoinn Design Group','Church','Protestant','Gwanghwamun','Religious','Free'],
    photos:[],
    drawings:[]
  },
  {
    id:'seoul-floating-islands',
    name:'Seoul Floating Islands (Some Sevit)',
    cat:'Parks & Public Spaces', cc:'c-park', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Haeahn Architecture + H Architecture', archs:['Haeahn Architecture'],
    yr:2014, access:'Free Admission', style:'Contemporary',
    lat:37.5123, lng:126.995,
    addr:'Banpo Hangang Park, Seocho-gu, Seoul', hood:'Banpo / Han River',
    desc:'Three artificial islands floating on the Han River adjacent to Banpo Bridge, Some Sevit (officially Sebitseom) were designed by Haeahn Architecture and H Architecture in New York as part of the Han River Renaissance initiative. Each island — Gavit, Chavit, and Solvit — is a self-contained structure on a buoy system with dynamic positioning technology for stability. The islands house performance venues, restaurants, and exhibition spaces, and glow dramatically at night. They are the world\'s first habitable floating structures of this scale.',
    hours:'Daily 10:00 AM – 11:00 PM (restaurants/venues vary)',
    lastEntry:'',
    admission:'Free (grounds) · Venue tickets vary',
    tourOk:false, tourInfo:'The islands are freely walkable. Food, beverage, and events are separately ticketed.',
    web:'https://www.somesevit.com/en',
    transit:'3 9 → Express Bus Terminal (Exit 4, 10-min walk along Han River)',
    walkFrom:'Banpo Bridge: 5 min · Banpo Hangang Park: directly connected',
    gmaps:'https://maps.google.com/?q=Some+Sevit+Floating+Islands+Seoul',
    archdaily:'https://www.archdaily.com/252931/seoul-floating-islands-haeahn-architecture-h-architecture',
    wiki:'https://en.wikipedia.org/wiki/Sebitseom',
    tags:['Haeahn Architecture','Floating','Han River','Banpo','Public','Night View'],
    photos:[],
    drawings:[]
  },
  {
    id:'kring-kumho',
    name:'KRING Kumho Cultural Complex',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Unsangdong Architects', archs:['Unsangdong Architects'],
    yr:2008, access:'Free Admission', style:'Contemporary',
    lat:37.5045512, lng:127.0646739,
    addr:'968-3 Daechi-dong, Gangnam-gu, Seoul', hood:'Daechi-dong / Gangnam',
    desc:'KRING is Kumho Asiana\'s cultural and creative complex in Gangnam, designed by Unsangdong Architects and completed in 2008. The building\'s steel-clad facade is punctured by circular apertures of varying scale, creating an organic rhythm that reads as a field of bubbles. A cylindrical skylit walkway connects the various programme levels — offices, conference rooms, a café, and a flexible performance and exhibition hall that hosts public cultural events, concerts, and brand activations throughout the year.',
    hours:'Mon–Fri 10:00 AM – 6:00 PM · Events vary',
    lastEntry:'',
    admission:'Free (lobby and public events)',
    tourOk:false, tourInfo:'Public ground floor and events are freely accessible.',
    web:'',
    transit:'3 → Daechi (Exit 4, 5-min walk) · 2 → Seolleung (15-min walk)',
    walkFrom:'Daechi Station: 5 min',
    gmaps:'https://maps.google.com/?q=KRING+Kumho+Cultural+Complex+Daechi-dong+Seoul',
    archdaily:'https://www.archdaily.com/66959/kring-kumho-culture-complex-unsangdong-architects',
    wiki:'',
    tags:['Unsangdong Architects','Cultural Complex','Gangnam','Kumho','Daechi'],
    photos:[],
    drawings:[]
  },
  {
    id:'su-o-jae',
    name:'Su-o-jae (Eunpyeong)',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'studio_GAON', archs:['studio_GAON'],
    yr:2017, access:'Private (Exterior Viewable)', style:'Contemporary / Vernacular',
    lat:37.6305, lng:126.928,
    addr:'Jingwan-dong, Eunpyeong-gu, Seoul', hood:'Eunpyeong / Jingwan-dong',
    desc:'Su-o-jae is a 98 m² private residence in the hilly northwestern district of Eunpyeong designed by studio_GAON and completed in 2017. The project negotiates the tension between a traditional Korean sensibility and contemporary construction: its massed stone base, deep eaves, and layered interior courts recall the han-ok typology while using entirely contemporary materials and structural logic. The building embodies studio_GAON\'s consistent investigation into the intersections of Korean spatial culture and modern architecture.',
    hours:'Private residence',
    lastEntry:'',
    admission:'Private — exterior viewable from street',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'3 → Gupabal (Exit 2) + Bus or taxi to Jingwan-dong',
    walkFrom:'Bukhansan Jingwan entrance: 10 min',
    gmaps:'https://maps.google.com/?q=Jingwan-dong+Eunpyeong-gu+Seoul',
    archdaily:'https://www.archdaily.com/888863/su-o-jae-in-eunpyeong-studio-gaon',
    wiki:'',
    tags:['studio_GAON','Residential','Vernacular','Eunpyeong','Hanok','Contemporary'],
    photos:[],
    drawings:[]
  },
  {
    id:'shinhan-expace',
    name:'Shinhan EX:PACE',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Atelier KI JUN KIM + Studio in Loco', archs:['Atelier KI JUN KIM'],
    yr:2021, access:'Free Admission', style:'Contemporary',
    lat:37.5614, lng:126.9888,
    addr:'Myeong-dong, Jung-gu, Seoul', hood:'Myeong-dong',
    desc:'Shinhan EX:PACE is the result of a radical facade transformation of a 1992 office building in the heart of Myeong-dong, completed in 2021 by Seoul-based Atelier KI JUN KIM and Studio in Loco. The undulating aluminium facade — composed of interlocking parametric panels — wraps the existing concrete structure like a second skin, turning a nondescript commercial block into a landmark presence on two crossing streets. The renovation also reorganised the interior to accommodate Shinhan Bank\'s public innovation hub alongside tech company co-working spaces.',
    hours:'Mon–Fri 9:00 AM – 6:00 PM',
    lastEntry:'',
    admission:'Lobby and exterior: Free',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'4 → Myeongdong (Exit 6, 3-min walk)',
    walkFrom:'Namdaemun Market: 8 min · Seoul City Hall: 10 min',
    gmaps:'https://maps.google.com/?q=Shinhan+Myeongdong+EX:PACE+Seoul',
    archdaily:'https://www.archdaily.com/963909/shinhan-ex-pace-atelier-ki-jun-kim-plus-studio-in-loco',
    wiki:'',
    tags:['Atelier KI JUN KIM','Facade','Renovation','Myeongdong','Parametric','Contemporary'],
    photos:[],
    drawings:[]
  },
  {
    id:'communique-hq',
    name:'Communique Headquarters',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'DaeWha Kang Design', archs:['DaeWha Kang Design'],
    yr:2015, access:'Private (Exterior Viewable)', style:'Contemporary / Adaptive Reuse',
    lat:37.5309, lng:126.9708,
    addr:'Yongsan-gu, Seoul', hood:'Yongsan',
    desc:'The Communique Headquarters in Yongsan is a full recladding and gut renovation of a neglected 1980s office building by DaeWha Kang Design, completed in 2015. The transformation is defined by its tessellated stainless steel crystalline cladding beneath the original building overhang — an abandoned car park reborn as a glittering reflective pavilion. The exterior was reclad entirely in intricate granite panels, and a new rooftop event space and ground floor café were added. The project won the 2015 Ministry of Land Award for best Adaptive Reuse in Korea.',
    hours:'Office building — exterior freely viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'https://daewha.com/portfolio/communique-headquarters/',
    transit:'6 → Noksapyeong (Exit 1, 10-min walk)',
    walkFrom:'Itaewon: 12 min',
    gmaps:'https://maps.google.com/?q=Communique+Headquarters+Yongsan+Seoul',
    archdaily:'https://www.archdaily.com/780596/communique-headquarters-daewha-kang-design',
    wiki:'',
    tags:['DaeWha Kang Design','Adaptive Reuse','Yongsan','Steel Facade','Award'],
    photos:[],
    drawings:[]
  },
  {
    id:'hankook-technoplex',
    name:'Hankook Technoplex',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'High-Tech',
    era:'2000–Present', city:'seoul',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2020, access:'Private (Exterior Viewable)', style:'High-Tech',
    lat:37.4027982, lng:127.1060014,
    addr:'Pangyo Techno Valley, Bundang-gu, Seongnam, Gyeonggi-do', hood:'Pangyo (Greater Seoul)',
    desc:'Hankook Tire\'s global R&D headquarters in Pangyo Techno Valley, designed by Foster + Partners and completed in 2020, organises four research towers and support facilities around a generous central atrium filled with biophilic greenery. The project, which Foster + Partners have described as a "city within a building," uses a continuous structural diagrid and a central park-like indoor landscape to support cross-disciplinary collaboration. Located in Pangyo — the tech hub adjacent to Seoul — the complex represents a new model for corporate research campuses in South Korea.',
    hours:'Private R&D facility — exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'https://www.fosterandpartners.com/projects/hankook-technoplex/',
    transit:'Sinbundang Line → Pangyo Station (15-min taxi)',
    walkFrom:'Pangyo Techno Valley: 5 min',
    gmaps:'https://maps.google.com/?q=Hankook+Technoplex+Pangyo',
    archdaily:'https://www.archdaily.com/948211/hankook-technoplex-foster-plus-partners',
    wiki:'',
    tags:['Foster + Partners','High-Tech','Pangyo','R&D','Biophilic','Corporate'],
    photos:[],
    drawings:[]
  },
  {
    id:'la-cucina',
    name:'La Cucina (Myeongborang)',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Choon Choi Architects', archs:['Choon Choi Architects'],
    yr:2019, access:'Restaurant / Commercial', style:'Contemporary',
    lat:37.5372, lng:127.0025,
    addr:'Hannam-dong, Yongsan-gu, Seoul', hood:'Hannam-dong',
    desc:'La Cucina Myeongborang, designed by Choon Choi Architects, occupies a commanding position at the highest point of Hannam-dong on the southern slopes of Namsan, with panoramic views from the Han River to N Seoul Tower. The building merges two distinct brand identities — Myeongborang, a boutique jewellery gallery founded in 1975, and La Cucina, an upscale Italian restaurant — within a single architectural envelope. The facade alternates between silver and champagne gold panels to express each brand\'s character while reading as a unified whole.',
    hours:'Restaurant hours: Lunch 11:30 AM – 2:30 PM · Dinner 6:00 PM – 10:00 PM',
    lastEntry:'',
    admission:'Restaurant / Gallery',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'6 → Hangangjin (Exit 1, 10-min walk uphill)',
    walkFrom:'Leeum Museum: 7 min · Itaewon: 12 min',
    gmaps:'https://maps.google.com/?q=La+Cucina+Myeongborang+Hannam-dong+Seoul',
    archdaily:'https://www.archdaily.com/939945/la-cucina-myeongborang-choon-choi-architects',
    wiki:'',
    tags:['Choon Choi Architects','Restaurant','Hannam-dong','Jewelry','Namsan View'],
    photos:[],
    drawings:[]
  },
  {
    id:'pino-familia',
    name:'Pino Familia',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Expressive',
    era:'2000–Present', city:'seoul',
    arch:'Moon Hoon', archs:['Moon Hoon'],
    yr:2016, access:'Paid Ticket', style:'Expressive / Narrative',
    lat:37.6313, lng:127.0726,
    addr:'131-17 Junggye-ro, Nowon-gu, Seoul', hood:'Junggye-dong / Nowon',
    desc:'Pino Familia is a private museum complex dedicated to a Pinocchio doll collection, designed by South Korean architect Moon Hoon and completed in 2016. Three distinct buildings — "Wave and Whale," "Whale Tale," and "The Nose Fountain" — are arranged around a central park with a large Pinocchio statue. Each structure responds to a specific Pinocchio narrative: the wave-shaped roof of the first building references the sea storm, while the nose fountain literalises the character\'s most iconic feature. The project is a signature work of Moon Hoon\'s playful, narrative-driven architecture.',
    hours:'Tue–Sun 10:00 AM – 6:00 PM',
    lastEntry:'5:00 PM',
    admission:'From ₩5,000',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'7 → Junggye (Exit 4, 10-min walk)',
    walkFrom:'Junggye Station: 10 min',
    gmaps:'https://maps.google.com/?q=Pino+Familia+Nowon+Seoul',
    archdaily:'https://www.archdaily.com/799660/pino-familia-moon-hoon',
    wiki:'',
    tags:['Moon Hoon','Museum','Pinocchio','Nowon','Narrative Architecture','Playful'],
    photos:[],
    drawings:[]
  },
  {
    id:'dance-of-light',
    name:'Dance of Light Installation',
    cat:'Parks & Public Spaces', cc:'c-park', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Naruse Inokuma Architects + a round architects', archs:['Naruse Inokuma Architects'],
    yr:2019, access:'Free Admission', style:'Public Art / Installation',
    lat:37.5348961, lng:126.9866323,
    addr:'Noksapyeong Station, Itaewon-ro, Yongsan-gu, Seoul', hood:'Noksapyeong / Itaewon',
    desc:'Dance of Light is a permanent public installation within Noksapyeong Station, created by Tokyo-based Naruse Inokuma Architects and local firm a round architects following a Seoul Metropolitan Government competition in 2016, completed in 2019. A 35-metre-deep main hall is transformed by a vast dome of expanded metal suspended in the atrium — the lattice catches and scatters sunlight filtering through the glass ceiling above, turning the underground space into a luminous canvas that changes with the hour. The installation was part of the wider revitalisation of Noksapyeong as a gateway to the neighbouring Bukchon Hangang Park.',
    hours:'Station hours: approx 5:30 AM – midnight daily',
    lastEntry:'',
    admission:'Free (accessible with transit fare)',
    tourOk:false, tourInfo:'Visible from the station concourse.',
    web:'',
    transit:'6 → Noksapyeong (Exit 2)',
    walkFrom:'Itaewon: 5 min · Leeum Museum: 8 min',
    gmaps:'https://maps.google.com/?q=Noksapyeong+Station+Seoul',
    archdaily:'https://www.archdaily.com/930351/dance-of-light-installation-naruse-inokuma-architects-plus-a-round-architects',
    wiki:'',
    tags:['Naruse Inokuma','Public Art','Subway','Light','Installation','Free'],
    photos:[],
    drawings:[]
  },
  {
    id:'juunj-flagship',
    name:'Juun.J Flagship Store',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'WGNB', archs:['WGNB'],
    yr:2019, access:'Free Admission', style:'Contemporary',
    lat:37.5256, lng:127.0283,
    addr:'23 Eonju-ro 164-gil, Sinsa-dong, Gangnam-gu, Seoul', hood:'Sinsa-dong / Dosan Park',
    desc:'The flagship store for Korean fashion designer Juun.J, designed by WGNB and completed in 2019, occupies an all-black rendered building in the leafy Sinsa-dong neighbourhood near Dosan Park. The project is composed of three primary geometric forms: a circle, a quadrangle, and a triangle. A glazed circular courtyard anchors the entry, while a steep triangular roof sweeps dramatically over an adjacent café volume. The building\'s stark geometry and monochromatic palette embody the brand\'s menswear aesthetic — precise, architectural, and quietly confrontational.',
    hours:'Daily 11:00 AM – 8:00 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'https://www.juunj.com',
    transit:'3 → Sinsa (Exit 8, 10-min walk)',
    walkFrom:'Dosan Park: 3 min · Garosu-gil: 7 min',
    gmaps:'https://maps.google.com/?q=Juun.J+Flagship+Store+Sinsa-dong+Seoul',
    archdaily:'https://www.archdaily.com/920562/juu-flagship-store-wgnb',
    wiki:'',
    tags:['WGNB','Fashion','Flagship Store','Sinsa-dong','All-Black','Dosan Park'],
    photos:[],
    drawings:[]
  },
  {
    id:'dr-jart-flagship',
    name:'Dr. Jart+ Filter Space',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Betwin Space Design', archs:['Betwin Space Design'],
    yr:2016, access:'Free Admission', style:'Contemporary',
    lat:37.5257, lng:127.0287,
    addr:'Dosan-daero, Sinsa-dong, Gangnam-gu, Seoul', hood:'Gangnam / Garosu-gil',
    desc:'Filter Space is the global flagship for Korean beauty brand Dr. Jart+, designed by Betwin Space Design and opened in 2016 on Garosu-gil. The entire building is conceived as an enormous filtration device — a metaphor for the brand\'s purification philosophy. The structure is wrapped in punched stainless steel panels that read as a filter during the day, while at night the inner illuminated form is exposed through the perforations. A large air-conditioning system on the rooftop, designed with the same aesthetic rigour, extends the industrial filtration metaphor across the skyline.',
    hours:'Daily 10:00 AM – 8:00 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'https://www.drjart.com',
    transit:'3 → Sinsa (Exit 8, 8-min walk) · 9 → Sinnonhyeon (10-min walk)',
    walkFrom:'Garosu-gil: directly on the street · Dosan Park: 5 min',
    gmaps:'https://maps.google.com/?q=Dr+Jart+Filter+Space+Garosu-gil+Seoul',
    archdaily:'https://www.archdaily.com/801738/dr-jart-plus-flagship-store-betwin-space-design',
    wiki:'',
    tags:['Betwin Space Design','Beauty','Flagship','Garosu-gil','Stainless Steel','Filter'],
    photos:[],
    drawings:[]
  },
  {
    id:'hicc-hq',
    name:'HiCC Entertainment HQ',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'LESS Architects', archs:['LESS Architects'],
    yr:2018, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.5267, lng:126.9042,
    addr:'Yeongdeungpo-gu, Seoul', hood:'Yeongdeungpo',
    desc:'The HiCC Entertainment headquarters, designed by LESS Architects, was conceived as a fluid, dynamic building that reflects its client\'s identity as a K-pop entertainment company. In contrast to the conventional static commercial block, LESS created a curvilinear massing that appears to shift and flow, with a facade that responds to the building\'s programme and orientation. The project emphasises the performative nature of entertainment culture through an architecture that prioritises movement and experiential variety over rigid geometry.',
    hours:'Private office — exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'2 5 → Yeongdeungpo-gu Office (5-min walk)',
    walkFrom:'Yeouido: 15 min · 63 Building: 15 min',
    gmaps:'https://maps.google.com/?q=HiCC+Entertainment+Seoul',
    archdaily:'https://www.archdaily.com/895964/hicc-ent-headquarter-less',
    wiki:'',
    tags:['LESS Architects','Entertainment','K-Pop','Contemporary','Corporate'],
    photos:[],
    drawings:[]
  },
  {
    id:'kolon-one-only-tower',
    name:'Kolon One & Only Tower',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'High-Tech',
    era:'2000–Present', city:'seoul',
    arch:'Morphosis (Thom Mayne)', archs:['Morphosis'],
    yr:2018, access:'Private (Exterior Viewable)', style:'High-Tech / Parametric',
    lat:37.5646, lng:126.8349,
    addr:'Magok, Gangseo-gu, Seoul', hood:'Magok Techno Valley',
    desc:'The Kolon One & Only Tower in Magok, Seoul is Morphosis\'s first completed building in South Korea, delivered in 2018 for Kolon Industries — a global leader in high-performance textiles and materials. The 820,000 sq ft campus weaves five-acre research, manufacturing, and office facilities into a cohesive whole. The facade is composed of reinforced composite fibre panels — the very material Kolon manufactures — creating a bespoke cladding that simultaneously performs structurally, thermally, and as a programmatic expression of the client\'s identity. The building\'s massing steps and shifts across the site adjacent to Magok\'s central park.',
    hours:'Private R&D campus — exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'https://www.morphosis.com/architecture/261/',
    transit:'5 9 → Magok Naru (Exit 4, 10-min walk)',
    walkFrom:'Magok Techno Valley: 8 min',
    gmaps:'https://maps.google.com/?q=Kolon+One+Only+Tower+Magok+Seoul',
    archdaily:'https://www.archdaily.com/900774/kolon-one-and-only-tower-morphosis-architects',
    wiki:'',
    tags:['Morphosis','Thom Mayne','High-Tech','Magok','Composite Fibre','Research','Campus'],
    photos:[],
    drawings:[]
  },
  {
    id:'wap-art-space',
    name:'WAP Art Space',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Davide Macullo Architects', archs:['Davide Macullo Architects'],
    yr:2017, access:'Free Admission', style:'Contemporary',
    lat:37.5236, lng:127.0561,
    addr:'Gangnam-gu, Seoul', hood:'Gangnam',
    desc:'WAP Art Space, designed by Swiss architect Davide Macullo and completed in 2017, is a private art foundation and gallery occupying the ground and basement floors of a seven-storey mixed-use building in Gangnam. The building\'s form is a three-dimensional composition of stacked concrete boxes arranged on an orthogonal 2-metre cubic grid, creating a legible system of volumes that stack and cantilever across the 815 m² site. Six exhibition rooms of diverse scale are organised around a sunken patio, bringing natural light into the lowest gallery level.',
    hours:'Tue–Sat 10:00 AM – 6:00 PM',
    lastEntry:'5:30 PM',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'http://www.wapartspace.com',
    transit:'3 → Sinsa (Exit 8, 8-min walk)',
    walkFrom:'Dosan Park: 5 min',
    gmaps:'https://maps.google.com/?q=WAP+Art+Space+Gangnam+Seoul',
    archdaily:'https://www.archdaily.com/899414/wap-art-space-davide-macullo-architects',
    wiki:'',
    tags:['Davide Macullo','Art Foundation','Gallery','Gangnam','Concrete','Swiss'],
    photos:[],
    drawings:[]
  },
  {
    id:'mc-building',
    name:'M.C. Building',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'URCODE Architecture', archs:['URCODE Architecture'],
    yr:2018, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.5040065, lng:127.0545244,
    addr:'895-13 Daechi-dong, Gangnam-gu, Seoul', hood:'Daechi-dong / Gangnam',
    desc:'The M.C. Building in Daechi-dong, Gangnam is a mixed-use commercial building by URCODE Architecture, completed in 2018 with a total floor area of 1,820 m². The site presents a narrow face to the street with its longer dimension running perpendicular, requiring a clever sectional strategy: the building is entered from both the first and second floors via a central stair hall and elevator core. The design emphasises flexibility — open-plan floors are divisible for restaurants, offices, or studio uses — and uses a restrained palette of concrete and glass that allows programme to drive the spatial experience.',
    hours:'Commercial building — exterior freely viewable',
    lastEntry:'',
    admission:'Commercial',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'3 → Daechi (Exit 3, 5-min walk)',
    walkFrom:'Daechi Station: 5 min · KRING Kumho: 5 min',
    gmaps:'https://maps.google.com/?q=895-13+Daechi-dong+Gangnam-gu+Seoul',
    archdaily:'https://www.archdaily.com/895788/mc-building-urcode-architecture',
    wiki:'',
    tags:['URCODE Architecture','Mixed-Use','Daechi-dong','Gangnam','Commercial'],
    photos:[],
    drawings:[]
  },
  {
    id:'samsung-seocho',
    name:'Samsung Seocho Building',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'KPF (Kohn Pedersen Fox) + Samoo Architects', archs:['KPF (Kohn Pedersen Fox)'],
    yr:2017, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.4967843, lng:127.0257872,
    addr:'1320 Seocho-daero, Seocho-gu, Seoul', hood:'Seocho-gu / Samsung Town',
    desc:'Samsung Town in Seocho is a major corporate campus comprising three towers — 44, 34, and 32 stories — housing Samsung Electronics, Samsung C&T, and Samsung Life Insurance respectively. Designed by KPF with associate architect Samoo and completed in 2017, the complex totals 239,000 m² and sets a new standard for large-scale Korean corporate headquarters. The towers are unified by a shared podium and landscaped public realm, and the composition prioritises a strong urban edge along Seocho-daero while creating sheltered pedestrian spaces at ground level.',
    hours:'Corporate campus — exterior and ground floor publicly accessible',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'https://www.samsung.com',
    transit:'2 → Seocho (Exit 6, 5-min walk) · 9 → Sinnonhyeon (10-min walk)',
    walkFrom:'Seocho Station: 5 min',
    gmaps:'https://maps.google.com/?q=Samsung+Seocho+Town+Seoul',
    archdaily:'https://www.archdaily.com/898210/samsung-seocho-kpf',
    wiki:'https://en.wikipedia.org/wiki/Samsung_Town',
    tags:['KPF','Samsung','Corporate Campus','Seocho','High-Rise','Samoo'],
    photos:[],
    drawings:[]
  },
  {
    id:'seoul-coffee',
    name:'Seoul Coffee',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'LABOTORY', archs:['LABOTORY'],
    yr:2018, access:'Free Admission', style:'Contemporary / Adaptive Reuse',
    lat:37.5744, lng:126.9897,
    addr:'Ikseon-dong, Jongno-gu, Seoul', hood:'Ikseon-dong / Jongno',
    desc:'Seoul Coffee in Ikseon-dong is a careful restoration of a 1980s–1990s era urban fabric by LABOTORY, completed in 2018. The architects removed partition walls between adjacent houses to create a generous communal seating and gathering area, and stripped away the existing ceiling to replace it with a glass roof that floods the formerly dark interior with natural light. The project is part of the broader revitalisation of Ikseon-dong — a historic alley neighbourhood that has become one of Seoul\'s most beloved walkable districts, retaining the scale and materiality of older Korea while hosting contemporary programming.',
    hours:'Mon–Fri 10:00 AM – 9:00 PM · Sat–Sun 9:00 AM – 9:00 PM',
    lastEntry:'',
    admission:'Café',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'1 3 5 → Jongno 3-ga (Exit 6, 5-min walk)',
    walkFrom:'Ikseon-dong alley: directly adjacent · Tapgol Park: 5 min',
    gmaps:'https://maps.google.com/?q=Seoul+Coffee+Ikseon-dong',
    archdaily:'https://www.archdaily.com/894606/seoul-coffee-labotory',
    wiki:'',
    tags:['LABOTORY','Café','Ikseon-dong','Adaptive Reuse','Hanok','Glass Roof'],
    photos:[],
    drawings:[]
  },
  {
    id:'yuhan-technos-hq',
    name:'Yuhan Technos HQ',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'MMKM Associates', archs:['MMKM Associates'],
    yr:2017, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.557, lng:126.8383,
    addr:'1 Magok-dong, Gangseo-gu, Seoul', hood:'Magok Techno Valley',
    desc:'The Yuhan Technos headquarters in Magok Techno Valley was designed by MMKM Associates and completed in 2017. The building occupies a prominent corner site in the emerging technology district in west Seoul and is defined by a distinctive origami-inspired facade of folded panels. The angular geometry reflects the precision manufacturing identity of the client while creating a dynamic elevation that changes character with shifting light and viewing angle. Magok is fast becoming one of Seoul\'s most architecturally ambitious districts, and the Yuhan Technos headquarters is among its early signature buildings.',
    hours:'Private — exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'5 9 → Magok Naru (Exit 4, 8-min walk)',
    walkFrom:'Kolon One & Only Tower: 5 min · Magok Central Park: 5 min',
    gmaps:'https://maps.google.com/?q=Yuhan+Technos+Magok+Seoul',
    archdaily:'https://www.arch2o.com/yuhantechnos-headquarter-mmkm-associates/',
    wiki:'',
    tags:['MMKM Associates','Magok','Corporate','Origami','Facade','Contemporary'],
    photos:[],
    drawings:[]
  },
  {
    id:'925-building',
    name:'925 Building',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'JHW IROJE architects & planners', archs:['JHW IROJE architects & planners'],
    yr:2015, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.5228, lng:127.0282,
    addr:'Cheongdam-dong, Gangnam-gu, Seoul', hood:'Cheongdam-dong / Gangnam',
    desc:'The 925 Building is a mixed-use commercial project by JHW IROJE architects & planners, completed in 2015 with a built area of 1,592 m². IROJE — the practice founded by Rha Woon-joo and known for a body of work spanning residential, cultural, and commercial projects across Seoul — treats the building\'s modest programme as an opportunity to test principles of mass, light, and materiality at an intimate urban scale. The result is a carefully composed facade that negotiates between the building\'s functional requirements and its responsibilities to the streetscape.',
    hours:'Commercial — exterior viewable',
    lastEntry:'',
    admission:'Commercial',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'7 → Cheongdam (Exit 13, 5-min walk)',
    walkFrom:'Dosan Park: 8 min · Galleria Department Store: 10 min',
    gmaps:'https://maps.google.com/?q=925+Building+Seoul',
    archdaily:'https://www.archdaily.com/889595/925-building-jhw-iroje-architects-and-planners',
    wiki:'',
    tags:['IROJE','Mixed-Use','Contemporary','Small Scale','Commercial'],
    photos:[],
    drawings:[]
  },
  {
    id:'atelier-chaeyeon',
    name:'Atelier Chaeyeon',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:"L'eau Design + Dongjin Kim", archs:["L'eau Design"],
    yr:2015, access:'Private (Exterior Viewable)', style:'Contemporary',
    lat:37.5256, lng:127.0281,
    addr:'Sinsa-dong, Gangnam-gu, Seoul', hood:'Sinsa-dong / Dosan Park',
    desc:"Atelier Chaeyeon is a small-scale creative studio and atelier project by Seoul-based L'eau Design in collaboration with Dongjin Kim, completed in 2015. The building embodies the sensibility of Seoul's emerging generation of micro-scale architectural interventions — projects that operate at the scale of a single programme type, pursuing clarity and refinement within tight constraints. The material language is spare and tactile, using texture and the modulation of natural light to create spatial richness within a compact envelope.",
    hours:'Private studio — exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'3 → Sinsa (Exit 8, 8-min walk)',
    walkFrom:'Dosan Park: 6 min · XYZ Formula: 3 min',
    gmaps:'https://maps.google.com/?q=Atelier+Chaeyeon+Seoul',
    archdaily:"https://www.archdaily.com/889413/atelier-chaeyeon-leau-design-plus-dongjin-kim",
    wiki:'',
    tags:["L'eau Design",'Atelier','Studio','Contemporary','Small Scale'],
    photos:[],
    drawings:[]
  },
  {
    id:'micro-cosmos-soyul',
    name:'Micro-Cosmos Soyul',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'KYWC Architects + Kim Seunghoy', archs:['KYWC Architects'],
    yr:2014, access:'Free Admission', style:'Contemporary',
    lat:37.5527, lng:126.9773,
    addr:'Huam-dong, Yongsan-gu, Seoul', hood:'Huam-dong / Namsan',
    desc:'Micro-Cosmos Soyul, designed by KYWC Architects and Seoul National University professor Kim Seunghoy and completed in 2014, is a small cultural space at the foot of Namsan in the dense residential neighbourhood of Huam-dong. The project is situated at the intersection of two alley conditions and responds to both street orientations through a carefully configured massing that opens towards the mountain above and the neighbourhood below. The building\'s name references both its modest scale and its ambition to contain a complete experiential universe within its compact programme.',
    hours:'Varies by programming',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'6 → Noksapyeong (Exit 2, 10-min walk)',
    walkFrom:'Namsan: 10 min · Itaewon: 12 min',
    gmaps:'https://maps.google.com/?q=Huam-dong+Yongsan-gu+Seoul',
    archdaily:'https://www.archdaily.com/885425/micro-cosmos-soyul-kywc-architects',
    wiki:'',
    tags:['KYWC Architects','Cultural Space','Huam-dong','Namsan','Small Scale','Free'],
    photos:[],
    drawings:[]
  },
  {
    id:'seoullo-7017',
    name:'SEOULLO 7017 Skygarden',
    cat:'Parks & Public Spaces', cc:'c-park', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'MVRDV', archs:['MVRDV'],
    yr:2017, access:'Free Admission', style:'Landscape / Adaptive Reuse',
    lat:37.5567026, lng:126.9710112,
    addr:'432 Toegye-ro, Jung-gu, Seoul', hood:'Seoul Station',
    desc:'SEOULLO 7017 is MVRDV\'s transformation of a 938-metre decommissioned elevated highway over Seoul Station into a linear public garden, opened in 2017 — the year 2017 referencing both its opening and the 1970 construction date of the original structure. Named after the 17 paths that now connect the elevated walkway to the surrounding streets, the garden features over 24,000 trees, shrubs, and plants organised by species in a living taxonomy. The project draws direct inspiration from New York\'s High Line and has become one of Seoul\'s most visited new public spaces.',
    hours:'Daily 24 hours (garden) · Visitor center: 9:00 AM – 9:00 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:true, tourInfo:'Self-guided maps available at the visitor center near Seoul Station. Guided walks on weekends.',
    web:'https://seoullo7017.co.kr/eng',
    transit:'1 4 → Seoul Station (Exit 2, 5-min walk) · AREX → Seoul Station',
    walkFrom:'Seoul Station: 5 min · Namdaemun Market: 10 min',
    gmaps:'https://maps.google.com/?q=SEOULLO+7017+Skygarden+Seoul',
    archdaily:'https://www.archdaily.com/tag/seoullo-7017',
    wiki:'https://en.wikipedia.org/wiki/Seoullo_7017',
    tags:['MVRDV','Elevated Park','Adaptive Reuse','Free','Seoul Station','Landscape','High Line'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Seoullo_7017%2C_Seoul%2C_Korea.jpg/800px-Seoullo_7017%2C_Seoul%2C_Korea.jpg'
    ],
    drawings:[]
  },
  {
    id:'xyz-formula',
    name:'XYZ Formula',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'WGNB', archs:['WGNB'],
    yr:2017, access:'Free Admission', style:'Contemporary',
    lat:37.5255, lng:127.0285,
    addr:'Sinsa-dong, Gangnam-gu, Seoul', hood:'Sinsa-dong / Dosan Park',
    desc:'XYZ Formula, designed by WGNB and completed in 2017, is a small mixed-use commercial project in the Sinsa-dong neighbourhood that demonstrates the Seoul-based firm\'s refined approach to materials and geometry at a boutique scale. The building is composed around a deceptively simple facade system that explores the interplay between solid and void, opaque and transparent surfaces, creating a layered street elevation that rewards close reading. WGNB\'s work across Sinsa-dong and the Dosan Park area has made the firm one of the defining architectural voices of contemporary Gangnam.',
    hours:'Commercial — varies by tenant',
    lastEntry:'',
    admission:'Commercial',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'3 → Sinsa (Exit 8, 10-min walk)',
    walkFrom:'Dosan Park: 5 min · Juun.J Flagship: 3 min',
    gmaps:'https://maps.google.com/?q=XYZ+Formula+Sinsa-dong+Seoul',
    archdaily:'https://www.archdaily.com/875995/xyz-formula-wgnb',
    wiki:'',
    tags:['WGNB','Sinsa-dong','Mixed-Use','Contemporary','Dosan Park','Small Scale'],
    photos:[],
    drawings:[]
  },
  {
    id:'leeum-museum',
    name:'Leeum Samsung Museum of Art',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000–Present', city:'seoul',
    arch:'Mario Botta · Jean Nouvel · Rem Koolhaas', archs:['Mario Botta','Jean Nouvel','Rem Koolhaas'],
    yr:2004, access:'Free Admission', style:'Contemporary',
    lat:37.5384, lng:126.9993,
    addr:'60-16 Itaewon-ro 55-gil, Yongsan-gu, Seoul', hood:'Hannam-dong / Itaewon',
    desc:'The Leeum Samsung Museum of Art in Hannam-dong is a rare collaboration of three of the 20th century\'s most prominent architects — Mario Botta, Jean Nouvel, and Rem Koolhaas — each commissioned to design a distinct building on the same hilltop campus, opened together in 2004. Botta\'s Museum 1 (Korean traditional art) is a terra-cotta and steel drum. Nouvel\'s Museum 2 (modern art) is a stainless steel and glass box. Koolhaas\'s Samsung Child Education & Culture Center is a black concrete volume. A fourth building, the Grand Hall, connects them. Closed for renovation 2021–2023, the museum reopened to international acclaim.',
    hours:'Tue–Sun 10:00 AM – 6:00 PM',
    lastEntry:'5:00 PM',
    admission:'Free (permanent collection) · Special exhibitions ticketed',
    tourOk:true, tourInfo:'Guided tours on weekends. Audio guides available in Korean, English, and Japanese.',
    web:'https://www.leeum.org/eng',
    transit:'6 → Hangangjin (Exit 1, 10-min walk uphill)',
    walkFrom:'Itaewon: 10 min · La Cucina Myeongborang: 7 min · Noksapyeong: 12 min',
    gmaps:'https://maps.google.com/?q=Leeum+Samsung+Museum+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Leeum_Samsung_Museum_of_Art',
    tags:['Mario Botta','Jean Nouvel','Rem Koolhaas','Museum','Free','Hannam-dong','Samsung'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Leeum_Samsung_Museum_of_Art.jpg/800px-Leeum_Samsung_Museum_of_Art.jpg'
    ],
    drawings:[]
  },
  {
    id:'ssamziegil',
    name:'Ssamziegil',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'GA.A Architects', archs:['GA.A Architects'],
    yr:2004, access:'Free Admission', style:'Contemporary / Commercial',
    lat:37.5743, lng:126.9849,
    addr:'44 Insadong-gil, Jongno-gu, Seoul', hood:'Insadong / Jongno',
    desc:'Ssamziegil, designed by GA.A Architects and opened in 2004, is an open-air multi-level commercial complex at the heart of Insadong that has become one of Seoul\u2019s most beloved cultural destinations. Rather than a conventional shopping mall, the architects conceived a spiral-ramped void at the centre of the block, allowing visitors to ascend continuously through four floors of independent boutiques, galleries, and caf\u00e9s without ever taking a staircase. The courtyard opens to the sky, turning natural light and the changing seasons into key architectural experiences. The design deliberately preserves the small-scale, artisanal character of Insadong \u2014 its resident vendors include independent craftspeople, indie labels, and local designers rather than chain retailers. Ssamziegil stands as one of the most successful examples of community-oriented commercial architecture in contemporary Seoul.',
    hours:'Daily 10:00 AM \u2013 9:00 PM',
    lastEntry:'',
    admission:'Free (commercial)',
    tourOk:false, tourInfo:'',
    web:'https://www.ssamziegil.com',
    transit:'3 \u2192 Anguk (Exit 6, 8-min walk) \u00b7 1 \u2192 Jonggak (Exit 3, 5-min walk)',
    walkFrom:'Jogyesa Temple: 8 min \u00b7 Changdeokgung Palace: 12 min \u00b7 Bukchon Hanok Village: 15 min',
    gmaps:'https://maps.google.com/?q=Ssamziegil+Insadong+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Ssamziegil',
    tags:['GA.A Architects','Insadong','Commercial','Spiral Ramp','Cultural','Free'],
    photos:[],
    drawings:[]
  },
  {
    id:'jongno-tower',
    name:'Jongno Tower',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'High-Tech',
    era:'1970\u20131999', city:'seoul',
    arch:'Rafael Vi\u00f1oly Architects + SAMOO', archs:['Rafael Vi\u00f1oly Architects','SAMOO'],
    yr:1999, access:'Lobby Viewable', style:'High-Tech / Late Modernist',
    lat:37.5707286, lng:126.9836336,
    addr:'51 Jong-ro, Jongno-gu, Seoul', hood:'Jonggak / CBD',
    desc:'Jongno Tower (Samsung Jong-ro Tower), designed by Rafael Vi\u00f1oly Architects in collaboration with SAMOO and completed in 1999, is one of the most architecturally distinctive office towers in central Seoul. The building\u2019s most striking feature is its three-storey glass observation platform \u2014 the \u201cNoodle\u201d \u2014 that cantilevers dramatically across the top of the 33-storey tower, spanning the full width of the building and floating above the city below. The structural expression of the tower is a showcase of late-20th-century high-tech sensibility: exposed trusses, perforated metal screens, and a formal language that celebrates the building\u2019s constructional logic. The tower is positioned at a historic and symbolic junction in Seoul, directly above Jonggak Station and within sight of the Jongno bell that has marked the centre of the city since the Joseon era.',
    hours:'Lobby accessible during business hours',
    lastEntry:'',
    admission:'Lobby free',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'1 \u2192 Jonggak (Exit 3, directly adjacent)',
    walkFrom:'Cheonggyecheon Stream: 5 min \u00b7 Jogyesa Temple: 8 min \u00b7 Gwanghwamun: 10 min',
    gmaps:'https://maps.google.com/?q=Jongno+Tower+Seoul',
    archdaily:'https://hiddenarchitecture.net/samsung-jong-no-tower/',
    wiki:'https://en.wikipedia.org/wiki/Jongno_Tower',
    tags:['Rafael Vi\u00f1oly','SAMOO','Office Tower','High-Tech','CBD','Cantilever'],
    photos:[],
    drawings:[]
  },
  {
    id:'kukje-gallery-k3',
    name:'Kukje Gallery K3',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'SO\u2013IL', archs:['SO\u2013IL','Florian Idenburg','Jing Liu'],
    yr:2012, access:'Free Admission', style:'Contemporary',
    lat:37.5796, lng:126.9791,
    addr:'54 Samcheong-ro, Jongno-gu, Seoul', hood:'Samcheong-dong',
    desc:'The K3 annex of Kukje Gallery, designed by SO\u2013IL (Florian Idenburg and Jing Liu) and completed in 2012, is a small yet internationally celebrated work of contemporary architecture in the Samcheong-dong gallery district. The building\u2019s defining gesture is its facade of chainmail: 510,000 individually welded stainless steel rings that drape over the volume like a textile, softening the boundary between inside and outside while creating a shimmering, material presence that changes character with the light throughout the day. Below ground, two floors of gallery, storage, and auditorium space support an intimate 16\u00d79\u00d76 m day-lit gallery at grade. The project demonstrated that a single material innovation, rigorously applied, could produce a building of genuine cultural resonance \u2014 and established SO\u2013IL as one of the most thoughtful Korean-American practices working internationally.',
    hours:'Tue\u2013Sat 10:00 AM \u2013 6:00 PM \u00b7 Sun 10:00 AM \u2013 5:00 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'https://www.kukjegallery.com',
    transit:'3 \u2192 Anguk (Exit 1, 10-min walk)',
    walkFrom:'Gyeongbokgung Palace: 10 min \u00b7 Bukchon Hanok Village: 8 min \u00b7 Changdeokgung: 15 min',
    gmaps:'https://maps.google.com/?q=Kukje+Gallery+K3+Samcheong-ro+Seoul',
    archdaily:'https://www.archdaily.com/237697/kukje-gallery-so-il',
    wiki:'',
    tags:['SO\u2013IL','Gallery','Chainmail','Samcheong-dong','Free','Florian Idenburg'],
    photos:[],
    drawings:[]
  },
  {
    id:'chungha-building',
    name:'Chungha Building',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'MVRDV', archs:['MVRDV'],
    yr:2013, access:'Free Admission', style:'Contemporary',
    lat:37.5238, lng:127.0287,
    addr:'Apgujeong-ro, Gangnam-gu, Seoul', hood:'Apgujeong / Gangnam',
    desc:'The Chungha Building on Apgujeong-ro was transformed by MVRDV in 2013 through the addition of an extra floor and a comprehensive facade redesign that gave the otherwise unremarkable commercial building a new identity. The project was completed in just nine months. MVRDV applied an irregular grid of deep, differently-sized window bays across the building\u2019s skin, creating a pixelated composition of solids and voids that plays with depth, shadow, and the perception of the building\u2019s volume from the street. The renovation exemplifies a practical model of architectural density: by working within the constraints of an existing structure, the project dramatically changes urban character without demolition or new land consumption. The building sits on one of Gangnam\u2019s most fashion-conscious retail streets, and its playful yet rigorous facade makes it immediately legible as a design statement.',
    hours:'Commercial \u2014 varies by tenant',
    lastEntry:'',
    admission:'Commercial',
    tourOk:false, tourInfo:'',
    web:'https://www.mvrdv.com/projects/26/chungha-building',
    transit:'3 \u2192 Apgujeong (Exit 2, 5-min walk)',
    walkFrom:'Dosan Park: 10 min \u00b7 Galleria Department Store: 5 min',
    gmaps:'https://maps.google.com/?q=Chungha+Building+Apgujeong+Seoul',
    archdaily:'https://www.archdaily.com/388669/chungha-building-mvrdv',
    wiki:'',
    tags:['MVRDV','Apgujeong','Renovation','Facade','Commercial','Gangnam'],
    photos:[],
    drawings:[]
  },
  {
    id:'boutique-monaco',
    name:'Boutique Monaco',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'Mass Studies', archs:['Mass Studies','Minsuk Cho','Kisu Park'],
    yr:2007, access:'Private (Exterior Viewable)', style:'Contemporary / Residential',
    lat:37.4974652, lng:127.024591,
    addr:'397 Seocho-daero, Seocho-gu, Seoul', hood:'Seocho-gu',
    desc:'Boutique Monaco is a 27-storey, 117-metre residential tower in Seocho-gu designed by Minsuk Cho and Kisu Park of Mass Studies, completed in 2007. The tower\u2019s distinctive silhouette is produced by 15 intentionally \u201cmissing\u201d spaces \u2014 recesses and voids cut from what would otherwise be a conventional slab tower \u2014 a strategy the architects used to comply with Seoul\u2019s floor area ratio regulations while simultaneously creating a more dynamic architectural form. The result is a porous, perforated volume that stands in direct contrast to the dense uniformity typical of Korean residential development. Boutique Monaco is widely cited as a seminal project in the emergence of Mass Studies as a practice, demonstrating how regulatory constraint can become a generative design tool. The building helped establish Minsuk Cho as one of the defining voices of Korean architecture in the 21st century.',
    hours:'Residential \u2014 exterior viewable',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'2 \u2192 Gangnam-gu Office (Exit 3, 10-min walk)',
    walkFrom:'Gangnam-daero: 5 min',
    gmaps:'https://maps.google.com/?q=Boutique+Monaco+Seocho+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Boutique_Monaco',
    tags:['Mass Studies','Minsuk Cho','Residential','Seocho-gu','Voids','FAR'],
    photos:[],
    drawings:[]
  },
  {
    id:'63-building',
    name:'63 Building',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Modernist',
    era:'1970\u20131999', city:'seoul',
    arch:'Skidmore, Owings & Merrill', archs:['Skidmore, Owings & Merrill'],
    yr:1985, access:'Paid Admission (Observatory)', style:'Late Modernist',
    lat:37.519872, lng:126.9402784,
    addr:'50 63-ro, Yeongdeungpo-gu, Seoul', hood:'Yeouido',
    desc:'The 63 Building on Yeouido Island was completed in 1985 and at the time of its opening was the tallest building outside North America, rising 249.6 metres above the Han River. Designed by Skidmore, Owings & Merrill, the tower was conceived as a landmark for the 1988 Seoul Olympics and became the defining image of South Korea\u2019s rapid economic modernisation during the 1970s and 1980s. Its gold-reflective glass curtain wall catches the light of the Han River and the Yeouido skyline in a way that has made it one of the most recognisable silhouettes in the city. Today it functions as a mixed-use complex \u2014 known as 63 Square \u2014 housing an aquarium, cinema, observation deck, and restaurants. The building is not only a piece of architectural history but a record of Seoul\u2019s ambition at one of its most transformative moments.',
    hours:'Daily 10:00 AM \u2013 10:00 PM',
    lastEntry:'9:30 PM',
    admission:'Observatory ticketed \u00b7 Aquarium ticketed',
    tourOk:false, tourInfo:'',
    web:'https://www.63.co.kr',
    transit:'5 9 \u2192 Yeouinaru (Exit 4, 8-min walk)',
    walkFrom:'Hangang Park Yeouido: 10 min \u00b7 S-Trenue Tower: 12 min',
    gmaps:'https://maps.google.com/?q=63+Building+Yeouido+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/63_Building',
    tags:['SOM','Yeouido','Skyscraper','Gold Glass','Han River','Olympics','1988'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/63building.jpg/800px-63building.jpg'
    ],
    drawings:[]
  },
  {
    id:'s-trenue-tower',
    name:'S-Trenue Tower',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'Mass Studies', archs:['Mass Studies','Minsuk Cho'],
    yr:2007, access:'Private (Lobby Viewable)', style:'Contemporary',
    lat:37.5228864, lng:126.9241315,
    addr:'26 Uisadang-daero, Yeongdeungpo-gu, Seoul', hood:'Yeouido',
    desc:'S-Trenue Tower in Yeouido, designed by Mass Studies (Minsuk Cho) and completed around 2007, is a 36-storey mixed-use building that Cho describes as a \u201cBundle Matrix\u201d \u2014 a composition of stacked and shifted volumetric bundles that challenges the uniformity of the conventional tower typology. The commercial lower floors give way to 113 officetel units above, with community facilities at mid-height. The building\u2019s massing is deliberately irregular: individual modules are rotated, offset, and differentiated to create a complex three-dimensional elevation that reads differently from every angle. S-Trenue stands alongside Boutique Monaco as one of Mass Studies\u2019 critical investigations into the Korean high-rise condition \u2014 using the constraints of programme, zoning, and structural economy as raw material for formal invention. Yeouido\u2019s grid of corporate towers makes the building\u2019s exuberance all the more striking.',
    hours:'Private \u2014 lobby viewable during business hours',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'5 9 \u2192 Yeouido (Exit 5, 10-min walk)',
    walkFrom:'63 Building: 10 min \u00b7 Hangang Park Yeouido: 8 min',
    gmaps:'https://maps.google.com/?q=S-Trenue+Tower+Yeouido+Seoul',
    archdaily:'https://www.archdaily.com/55868/s-trenue-tower-mass-studies',
    wiki:'',
    tags:['Mass Studies','Minsuk Cho','Yeouido','Bundle Matrix','Mixed-Use','Officetel'],
    photos:[],
    drawings:[]
  },
  {
    id:'seongdong-cultural-center',
    name:'Seongdong Cultural & Welfare Center',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'UnSangDong Architects', archs:['UnSangDong Architects','Jang Yoon Gyoo'],
    yr:2012, access:'Free Admission', style:'Contemporary',
    lat:37.5443, lng:127.0553,
    addr:'Seongsu-dong, Seongdong-gu, Seoul', hood:'Seongsu-dong',
    desc:'The Seongdong Cultural & Welfare Center, designed by UnSangDong Architects (Jang Yoon Gyoo, Shin Chang Hoon) and completed in 2012, is a civic complex in the Seongsu-dong district \u2014 an area historically known as the \u201cBrooklyn of Seoul\u201d for its concentration of craft workshops, leather ateliers, and light industrial heritage. The building stacks a library, fitness centre, welfare offices, and community gathering spaces within a compact urban block, using a sculpted facade system of perforated and folded metal panels that mediates between the building\u2019s civic ambitions and the rough industrial texture of its neighbourhood. UnSangDong\u2019s work characteristically explores the social and urban dimensions of public architecture in Seoul \u2014 treating civic buildings as activators of neighbourhood life rather than isolated monuments. The center anchors a stretch of Seongsu that has, since its completion, seen rapid transformation into one of the city\u2019s most design-forward districts.',
    hours:'Mon\u2013Fri 9:00 AM \u2013 10:00 PM \u00b7 Sat 9:00 AM \u2013 6:00 PM',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'',
    transit:'2 \u2192 Seongsu (Exit 3, 8-min walk)',
    walkFrom:'Seongsu-dong cafe street: 5 min \u00b7 Ttukseom Hangang Park: 15 min',
    gmaps:'https://maps.google.com/?q=Seongdong+Cultural+Welfare+Center+Seoul',
    archdaily:'https://www.archdaily.com/551478/seongdong-cultural-and-welfare-center-unsangdong-architects',
    wiki:'',
    tags:['UnSangDong','Seongsu-dong','Civic','Community','Free','Jang Yoon Gyoo'],
    photos:[],
    drawings:[]
  },
  {
    id:'amorepacific-hq',
    name:'Amorepacific Headquarters',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'David Chipperfield Architects', archs:['David Chipperfield Architects'],
    yr:2017, access:'Lobby & Atrium (Free)', style:'Contemporary',
    lat:37.5287873, lng:126.9686294,
    addr:'100 Hangang-daero, Yongsan-gu, Seoul', hood:'Yongsan',
    desc:'The Amorepacific Headquarters in Yongsan, designed by David Chipperfield Architects and completed in 2017, is one of the most significant corporate buildings completed in Seoul in the 21st century \u2014 a 23-storey, 90\u00d790-metre cube that sits at the edge of the former US military zone now being transformed into Yongsan Park. The building\u2019s defining feature is its triple-height \u201changing gardens\u201d \u2014 three monumental voids carved into the building at different levels, each containing a terrace and planted garden that bring light, sky, and greenery into the heart of the office floors. The facade is clad in a perforated aluminium screen that wraps the volume uniformly, softening the building\u2019s edges in daylight and glowing at night. A double-height public museum and gallery at ground level are open to visitors. The building is widely regarded as one of Chipperfield\u2019s finest works and a rare example of genuinely public-spirited corporate architecture in Seoul.',
    hours:'Museum: Tue\u2013Sun 10:00 AM \u2013 6:00 PM \u00b7 Lobby open during business hours',
    lastEntry:'5:30 PM (museum)',
    admission:'Museum free',
    tourOk:false, tourInfo:'',
    web:'https://www.amorepacific.com',
    transit:'1 4 \u2192 Sinyongsan (Exit 1, 5-min walk)',
    walkFrom:'Yongsan Station: 8 min \u00b7 National Museum of Korea: 15 min \u00b7 Leeum Museum: 12 min',
    gmaps:'https://maps.google.com/?q=Amorepacific+Headquarters+Yongsan+Seoul',
    archdaily:'https://www.archdaily.com/915298/amorepacific-headquarters-david-chipperfield-architects',
    wiki:'',
    tags:['David Chipperfield','Yongsan','Corporate','Hanging Gardens','Museum','Free','Facade'],
    photos:[],
    drawings:[]
  },
  {
    id:'gyeongbokgung-palace',
    name:'Gyeongbokgung Palace',
    cat:'Historic Buildings', cc:'c-his', styleGroup:'Traditional Korean',
    era:'Pre-1900', city:'seoul',
    arch:'Traditional Korean (Joseon Dynasty)', archs:['Traditional Korean'],
    yr:1395, access:'Paid Admission', style:'Traditional Korean Palace Architecture',
    lat:37.5796, lng:126.977,
    addr:'161 Sajik-ro, Jongno-gu, Seoul', hood:'Gyeongbokgung / Bukchon',
    desc:'Gyeongbokgung Palace, built in 1395 as the primary royal residence of the Joseon dynasty, is the largest and most iconic of Seoul\u2019s Five Grand Palaces. The complex extends across 40 hectares in the northern heart of the city, with Bukhansan mountain as its backdrop and the ceremonial axis of Gwanghwamun at its southern gate. The architecture follows the strict hierarchical principles of Confucian spatial organisation: concentric enclosures define zones of public ceremony, private royal life, and intimate garden, culminating in the Geunjeongjeon (Throne Hall) at the compound\u2019s ceremonial centre. Much of the palace was destroyed by the Japanese during the colonial period (1910\u20131945), and the decades-long reconstruction programme \u2014 still ongoing \u2014 has returned many key structures to their Joseon-era forms. Gyeongbokgung remains the most potent architectural expression of Korean sovereign identity and cultural continuity in the capital.',
    hours:'Tue\u2013Sun 9:00 AM \u2013 6:00 PM (Mar\u2013Oct to 6:30 PM)',
    lastEntry:'1 hr before closing',
    admission:'3,000 KRW (adults) \u00b7 Free on certain national holidays',
    tourOk:true, tourInfo:'Free guided tours in English available at 11:00 AM and 2:00 PM daily (Tuesday\u2013Sunday).',
    web:'https://www.royalpalace.go.kr',
    transit:'3 \u2192 Gyeongbokgung (Exit 5, 5-min walk)',
    walkFrom:'Gwanghwamun Square: 5 min \u00b7 Bukchon Hanok Village: 15 min \u00b7 National Folk Museum: on-site',
    gmaps:'https://maps.google.com/?q=Gyeongbokgung+Palace+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Gyeongbokgung',
    tags:['Joseon','Palace','Historic','UNESCO nominee','Hanok','Traditional','Free Tour'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Geunjeongjeon.jpg/800px-Geunjeongjeon.jpg'
    ],
    drawings:[]
  },
  {
    id:'changdeokgung-palace',
    name:'Changdeokgung Palace',
    cat:'Historic Buildings', cc:'c-his', styleGroup:'Traditional Korean',
    era:'Pre-1900', city:'seoul',
    arch:'Traditional Korean (Joseon Dynasty)', archs:['Traditional Korean'],
    yr:1405, access:'Paid Admission', style:'Traditional Korean Palace Architecture',
    lat:37.5794, lng:126.991,
    addr:'99 Yulgok-ro, Jongno-gu, Seoul', hood:'Changdeokgung / Bukchon',
    desc:'Changdeokgung Palace, built in 1405 as a secondary royal residence and today inscribed as a UNESCO World Heritage Site, is widely considered the finest surviving example of Joseon-era palace architecture in Korea. Unlike Gyeongbokgung\u2019s strict axial geometry, Changdeokgung follows the topography of its hillside site, with buildings and gardens arranged in organic harmony with the natural landscape. The complex is most famous for its Huwon (Secret Garden) \u2014 a 78-acre garden of ponds, pavilions, and ancient trees that was the private preserve of the royal family for centuries and remains one of the most extraordinary designed landscapes in East Asia. The main palace halls were burned and rebuilt multiple times during Korean history, but the overall spatial organisation and material palette of timber, tile, and stone have been preserved with exceptional fidelity. Changdeokgung is the most complete and intimate of Seoul\u2019s Five Grand Palaces.',
    hours:'Tue\u2013Sun 9:00 AM \u2013 6:00 PM (Mar\u2013Oct to 6:30 PM)',
    lastEntry:'1 hr before closing',
    admission:'3,000 KRW (palace) \u00b7 Secret Garden: 5,000 KRW (guided tour only)',
    tourOk:true, tourInfo:'Secret Garden tours are guided-only and must be booked in advance. English tours available at 11:30 AM and 2:30 PM (Tue\u2013Sun).',
    web:'https://www.cdg.go.kr',
    transit:'3 \u2192 Anguk (Exit 3, 5-min walk)',
    walkFrom:'Bukchon Hanok Village: 8 min \u00b7 Jongmyo Shrine: 12 min \u00b7 Insadong: 15 min',
    gmaps:'https://maps.google.com/?q=Changdeokgung+Palace+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Changdeokgung',
    tags:['Joseon','Palace','UNESCO','Secret Garden','Huwon','Historic','Traditional'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Changdeokgung-aft.jpg/800px-Changdeokgung-aft.jpg'
    ],
    drawings:[]
  },
  {
    id:'jongmyo-shrine',
    name:'Jongmyo Shrine',
    cat:'Religious Architecture', cc:'c-rel', styleGroup:'Traditional Korean',
    era:'Pre-1900', city:'seoul',
    arch:'Traditional Korean (Joseon Dynasty)', archs:['Traditional Korean'],
    yr:1395, access:'Paid Admission', style:'Confucian Ritual Architecture',
    lat:37.5744, lng:126.9942,
    addr:'157 Jong-ro, Jongno-gu, Seoul', hood:'Jongno / Insa-dong',
    desc:'Jongmyo Shrine, established in 1395 and inscribed as a UNESCO World Heritage Site, is the oldest and most authentic of East Asian royal Confucian shrines still in existence. The complex was built to house the memorial tablets of the kings and queens of the Joseon dynasty, and the main hall \u2014 Jeongjeon \u2014 is, at 101 metres, the longest wooden structure in Korea. Its austere, horizontal architecture deliberately avoids ornament in favour of an uncompromising formal solemnity: a single continuous eave carried on 49 stone columns enclosing an unbroken sequence of spirit chambers. The Jongmyo Jerye (royal ancestral rites), performed annually on the first Sunday of May and inscribed on UNESCO\u2019s Intangible Cultural Heritage list, transforms the otherwise silent precinct into a ceremony of music, dance, and ritual that has been performed without interruption for over 500 years. The architecture of Jongmyo is perhaps the most complete surviving expression of Confucian spatial philosophy anywhere in the world.',
    hours:'Tue\u2013Sun 9:00 AM \u2013 6:00 PM (closes 5:30 PM Nov\u2013Jan)',
    lastEntry:'1 hr before closing',
    admission:'1,000 KRW (adults)',
    tourOk:true, tourInfo:'Free guided tours available on weekdays at 10:00 AM, 12:00 PM, 2:00 PM, 4:00 PM. Free entry on Saturday.',
    web:'https://jm.cha.go.kr',
    transit:'1 3 5 \u2192 Jongno 3-ga (Exit 11, 5-min walk)',
    walkFrom:'Insadong: 8 min \u00b7 Changdeokgung Palace: 12 min \u00b7 Bukchon: 15 min',
    gmaps:'https://maps.google.com/?q=Jongmyo+Shrine+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Jongmyo',
    tags:['Joseon','UNESCO','Confucian','Shrine','Ritual','Historic','Traditional','Intangible Heritage'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Jongmyo_Jeongjeon.JPG/800px-Jongmyo_Jeongjeon.JPG'
    ],
    drawings:[]
  },
  {
    id:'bukchon-hanok-village',
    name:'Bukchon Hanok Village',
    cat:'Historic Buildings', cc:'c-his', styleGroup:'Traditional Korean',
    era:'Pre-1930', city:'seoul',
    arch:'Traditional Korean (Hanok)', archs:['Traditional Korean'],
    yr:1920, access:'Free Admission', style:'Traditional Korean Residential (Hanok)',
    lat:37.5826, lng:126.983,
    addr:'Gahoe-dong, Jongno-gu, Seoul', hood:'Bukchon / Gahoe-dong',
    desc:'Bukchon Hanok Village is a dense residential neighbourhood of over 900 traditional Korean hanok houses occupying the hillside between Gyeongbokgung and Changdeokgung palaces in the Jongno district. The majority of the surviving hanok were built during the early 20th century, when private developers subdivided the former aristocratic estates into smaller residential plots, producing the compact alley-and-courtyard urban fabric that defines the neighbourhood today. Each hanok follows the same organisational logic \u2014 rooms arranged around a courtyard, with tiled roofs extending in characteristic sweeping eaves \u2014 yet infinite variation in layout, detail, and age produces a streetscape of rich individuality. The area was under serious threat from demolition in the late 20th century, but sustained conservation efforts by the Seoul Metropolitan Government and resident organisations have preserved most of the urban fabric. Bukchon is today one of Seoul\u2019s most visited cultural destinations and a living study in the tension between preservation and tourism pressure.',
    hours:'Village freely accessible at all times',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'https://bukchon.seoul.go.kr',
    transit:'3 \u2192 Anguk (Exit 2, 10-min walk)',
    walkFrom:'Gyeongbokgung Palace: 12 min \u00b7 Changdeokgung Palace: 8 min \u00b7 Kukje Gallery K3: 8 min',
    gmaps:'https://maps.google.com/?q=Bukchon+Hanok+Village+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Bukchon_Hanok_Village',
    tags:['Hanok','Traditional','Conservation','Joseon','Residential','Free','UNESCO candidate'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bukchon_Hanok_Village.jpg/800px-Bukchon_Hanok_Village.jpg'
    ],
    drawings:[]
  },
  {
    id:'jogyesa-temple',
    name:'Jogyesa Temple',
    cat:'Religious Architecture', cc:'c-rel', styleGroup:'Traditional Korean',
    era:'1930\u20131969', city:'seoul',
    arch:'Traditional Korean Buddhist', archs:['Traditional Korean'],
    yr:1938, access:'Free Admission', style:'Traditional Korean Buddhist',
    lat:37.574, lng:126.982,
    addr:'55 Ujeongguk-ro, Jongno-gu, Seoul', hood:'Insadong / Jongno',
    desc:'Jogyesa Temple is the head temple of the Jogye Order of Korean Buddhism and the most prominent Buddhist temple in Seoul, with a history at the current site dating to 1395 and the main hall (Daeungjeon) built in 1938. The temple is unusual for a major Korean Buddhist complex in being embedded within the dense urban fabric of central Seoul rather than on a mountainside, and it fulfils a vital function as a daily place of worship, education, and cultural ceremony in the heart of the city. The Daeungjeon (Main Hall) is a designated national treasure, built in the Joseon palace style with sweeping tiled roofs and richly painted dancheong (multicoloured decorative paintwork) applied to its exposed timber structural members. The temple grounds contain a 500-year-old zelkova tree and a white pine of similar age, making them remarkable urban nature spaces as well as sacred architecture. During Buddha\u2019s Birthday celebrations (fourth month of the lunar calendar), the entire Insadong neighbourhood is lit by thousands of lanterns strung from the temple.',
    hours:'Daily open from dawn to dusk',
    lastEntry:'',
    admission:'Free',
    tourOk:false, tourInfo:'',
    web:'https://www.jogyesa.kr',
    transit:'3 \u2192 Anguk (Exit 6, 10-min walk) \u00b7 1 \u2192 Jonggak (Exit 2, 8-min walk)',
    walkFrom:'Insadong: 5 min \u00b7 Gyeongbokgung: 12 min \u00b7 Jongno Tower: 8 min',
    gmaps:'https://maps.google.com/?q=Jogyesa+Temple+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/Jogyesa',
    tags:['Buddhist','Temple','Traditional','Free','Insadong','Lantern Festival','National Treasure'],
    photos:[],
    drawings:[]
  },
  {
    id:'n-seoul-tower',
    name:'N Seoul Tower',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Modernist',
    era:'1970\u20131999', city:'seoul',
    arch:'Korean Broadcasting System (KBS)', archs:['Korean Broadcasting System'],
    yr:1975, access:'Paid Admission (Observatory)', style:'Modernist',
    lat:37.5512, lng:126.9882,
    addr:'105 Namsangongwon-gil, Yongsan-gu, Seoul', hood:'Namsan Mountain',
    desc:'N Seoul Tower (officially YTN Seoul Tower, known popularly as Namsan Tower) is a 236-metre communication and observation tower built on the summit of Namsan Mountain, a forested hill at the geographic centre of Seoul. Construction began in 1969 for broadcasting purposes and the tower opened to the public in 1975, becoming the first general-use observation tower in Korea. The tower rises from the mountain summit at 243 metres above sea level, giving its observation decks \u2014 at 236 metres \u2014 a total height of 479 metres above sea level, with views extending on clear days to the Han River estuary and the surrounding mountain ranges. The architecture of the tower itself is a functional exercise in Modernist infrastructure design, but its setting on Namsan \u2014 accessible via cable car, forest hiking trails, and a switchback road \u2014 makes the approach experience as remarkable as the destination. The tradition of \u201clove locks\u201d attached to the observation fences has become one of Seoul\u2019s most recognisable popular cultural traditions.',
    hours:'Sun\u2013Thu 10:00 AM \u2013 11:00 PM \u00b7 Fri\u2013Sat 10:00 AM \u2013 Midnight',
    lastEntry:'30 min before closing',
    admission:'Observatory: 21,000 KRW (adults)',
    tourOk:false, tourInfo:'',
    web:'https://www.nseoultower.com',
    transit:'Cable car from Myeongdong: 3 min \u00b7 3 \u2192 Chungmuro (Exit 2, 20-min walk + cable car)',
    walkFrom:'Myeongdong: 15 min walk + cable car \u00b7 Namsan Park: 5 min walk from tower',
    gmaps:'https://maps.google.com/?q=N+Seoul+Tower+Namsan',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/N_Seoul_Tower',
    tags:['Namsan','Observation Tower','Broadcasting','City View','Cable Car','Love Locks'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/N_Seoul_Tower_2.jpg/800px-N_Seoul_Tower_2.jpg'
    ],
    drawings:[]
  },
  {
    id:'national-museum-korea',
    name:'National Museum of Korea',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000\u2013Present', city:'seoul',
    arch:'Samoo Architects + Junglim Architecture', archs:['Samoo Architects','Junglim Architecture'],
    yr:2005, access:'Free Admission', style:'Contemporary',
    lat:37.523899, lng:126.9801897,
    addr:'137 Seobinggo-ro, Yongsan-gu, Seoul', hood:'Yongsan / Ichon-dong',
    desc:'The National Museum of Korea in Yongsan-gu, designed by Samoo Architects and Junglim Architecture and opened in 2005, is the largest museum in South Korea and one of the largest in Asia, with a collection of over 400,000 artefacts spanning Korean history from the Paleolithic period to the 19th century. The building occupies an 18-hectare site adjacent to Yongsan Family Park (the former US military recreational grounds), and its massing \u2014 a long, low horizontal block punctuated by three vertical stone towers \u2014 is designed to read as a modern interpretation of the traditional Korean palace typology. The main axis of the building extends 404 metres from the entrance gate to the rear garden, with the great hall at its centre opening to views of the park and Namsan beyond. Unlike many national museum buildings that use architecture to signal cultural prestige through grandeur, the NMK\u2019s designers chose a quieter, more contemplative tone \u2014 using natural stone, open courtyards, and restrained interior volumes to focus attention on the artefacts themselves.',
    hours:'Mon\u2013Thu\u2013Fri\u2013Sun 10:00 AM \u2013 6:00 PM \u00b7 Wed\u2013Sat 10:00 AM \u2013 9:00 PM',
    lastEntry:'1 hr before closing',
    admission:'Permanent collection free \u00b7 Special exhibitions ticketed',
    tourOk:true, tourInfo:'Free guided tours of the permanent collection in Korean, English, Chinese, and Japanese. English tours: Tue\u2013Fri 10:30 AM and 2:30 PM.',
    web:'https://www.museum.go.kr/site/eng/home',
    transit:'4 \u2192 Ichon (Exit 2, 3-min walk)',
    walkFrom:'Yongsan Family Park: adjacent \u00b7 Amorepacific HQ: 12 min',
    gmaps:'https://maps.google.com/?q=National+Museum+of+Korea+Seoul',
    archdaily:'',
    wiki:'https://en.wikipedia.org/wiki/National_Museum_of_Korea',
    tags:['Museum','Free','Yongsan','National Museum','History','Korean Heritage','Permanent Collection'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/National_Museum_of_Korea_at_night.jpg/800px-National_Museum_of_Korea_at_night.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/National_Museum_of_Korea_2.jpg/800px-National_Museum_of_Korea_2.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/National_Museum_of_Korea_-_panoramio.jpg/800px-National_Museum_of_Korea_-_panoramio.jpg'
    ],
    drawings:[]
  }

];
/* DATA_END */