/* ============================================================
   ArchWander Ã¢ÂÂ London Location Data
   19 locations ÃÂ· Foster + Partners ÃÂ· Richard Rogers ÃÂ· Renzo Piano
   Edit this file to add / modify London locations.
   ============================================================ */

const LOCS_LONDON = [

  // Ã¢ÂÂÃ¢ÂÂ FOSTER + PARTNERS Ã¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂ

  {
    id:'gherkin',
    name:'30 St Mary Axe (Gherkin)',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'High-Tech',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2003, access:'Free Admission', style:'High-Tech',
    lat:51.5145, lng:-0.0803,
    addr:'30 St Mary Axe, City of London EC3A 8EP', hood:'City of London',
    desc:'The Gherkin is London\'s most recognisable tower, its 180-metre bullet-shaped profile rising above the medieval street grid of the City. Designed by Foster + Partners for Swiss Re and completed in 2003, the diagrid structural frame eliminates internal columns and creates column-free floor plates throughout. Six light wells spiral up the building\'s exterior, channelling natural ventilation through the offices and cutting energy consumption by roughly half compared to a conventional sealed tower. Unusually for a skyscraper, every panel of its diamond-patterned glass facade is flat, yet the geometry gives the illusion of a continuous curve.',
    hours:'Lobby: MonÃ¢ÂÂFri 7:00 AM Ã¢ÂÂ 7:00 PM ÃÂ· Upper floors: private',
    lastEntry:'',
    admission:'Free (lobby only) ÃÂ· Upper floors private',
    tourOk:true, tourInfo:'Open House London (September) grants public access to upper floors. The private dining room at the apex occasionally hosts corporate events visible through the glazed dome.',
    web:'https://www.30stmaryaxe.com',
    transit:'Circle District Ã¢ÂÂ Aldgate ÃÂ· Central Waterloo & City Ã¢ÂÂ Bank (5 min walk)',
    walkFrom:'Liverpool Street: 6 min ÃÂ· Lloyd\'s of London: 3 min ÃÂ· Leadenhall Market: 4 min',
    gmaps:'https://maps.google.com/?q=30+St+Mary+Axe+London',
    archdaily:'https://www.archdaily.com/tag/30-st-mary-axe',
    wiki:'https://en.wikipedia.org/wiki/30_St_Mary_Axe',
    tags:['Foster + Partners','Norman Foster','High-Tech','Diagrid','Swiss Re','Gherkin','Skyscraper','City of London','RIBA Stirling Prize'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/30_St_Mary_Axe_from_Leadenhall_Street.jpg/800px-30_St_Mary_Axe_from_Leadenhall_Street.jpg'
    ],
    drawings:[]
  },

  {
    id:'bloomberg-hq-london',
    name:'Bloomberg European HQ',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2017, access:'Free Admission', style:'Contemporary',
    lat:51.5122, lng:-0.0912,
    addr:'3 Queen Victoria Street, City of London EC4N 4TQ', hood:'City of London',
    desc:'Widely regarded as the world\'s most sustainable office building, Bloomberg\'s European headquarters received the highest ever BREEAM Outstanding score of 98.5% at the time of its completion. Foster + Partners\'s design reinstates a Roman-era street Ã¢ÂÂ Watling Street Ã¢ÂÂ through the site and incorporates some 16,000 bronze petal-shaped fins on its curved facade that open and close to regulate airflow. Beneath the building, a permanent public exhibition displays the remains of London\'s Roman Temple of Mithras, excavated on the same site in the 1950s.',
    hours:'Ground floor arcade & Mithraeum: daily ÃÂ· Offices: private',
    lastEntry:'',
    admission:'Free (arcade and Mithraeum museum)',
    tourOk:true, tourInfo:'The London Mithraeum in the basement is free to visit and open to the public. The building interior can be visited during Open House London.',
    web:'https://www.londonmithraeum.com',
    transit:'Central Ã¢ÂÂ Bank (2 min) ÃÂ· Circle District Ã¢ÂÂ Mansion House (3 min)',
    walkFrom:'St Paul\'s Cathedral: 5 min ÃÂ· Tate Modern: 10 min ÃÂ· Bank: 3 min',
    gmaps:'https://maps.google.com/?q=Bloomberg+European+HQ+London',
    archdaily:'https://www.archdaily.com/880369/bloomberg-london-foster-and-partners',
    wiki:'https://en.wikipedia.org/wiki/Bloomberg_London',
    tags:['Foster + Partners','Bloomberg','BREEAM','Sustainable','Mithraeum','Roman','City of London','RIBA Stirling Prize 2018'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bloomberg_London.jpg/800px-Bloomberg_London.jpg'
    ],
    drawings:[]
  },

  {
    id:'great-court-british-museum',
    name:'Great Court, British Museum',
    cat:'Museums & Culture', cc:'c-mus', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2000, access:'Free Admission', style:'Contemporary',
    lat:51.5194, lng:-0.1270,
    addr:'Great Russell Street, Bloomsbury, London WC1B 3DG', hood:'Bloomsbury',
    desc:'The Queen Elizabeth II Great Court transformed the long-neglected inner courtyard of the British Museum into Europe\'s largest covered public square. Foster + Partners\'s steel-and-glass roof Ã¢ÂÂ a 3,312-panel gridshell no two panes of which are identical Ã¢ÂÂ spans the 2-acre courtyard and encloses the iconic circular Reading Room at its centre. Completed in 2000 for the museum\'s 250th anniversary, the roof resolves the previously impossible geometry of fitting a circular room inside a rectangular courtyard through parametric design that predated mainstream computational tools.',
    hours:'Daily 10:00 AM Ã¢ÂÂ 5:30 PM (Fri to 8:30 PM) ÃÂ· Great Court open from 9:00 AM',
    lastEntry:'5:00 PM',
    admission:'Free (Great Court and permanent collection) ÃÂ· Paid for special exhibitions',
    tourOk:true, tourInfo:'Free highlights tours of the permanent collection depart from the Great Court regularly. The Reading Room is open to the public on selected dates.',
    web:'https://www.britishmuseum.org',
    transit:'Central Piccadilly Ã¢ÂÂ Holborn (3 min) ÃÂ· Northern Ã¢ÂÂ Tottenham Court Road (5 min)',
    walkFrom:'Tottenham Court Road: 5 min ÃÂ· Covent Garden: 10 min ÃÂ· Oxford Street: 8 min',
    gmaps:'https://maps.google.com/?q=British+Museum+London',
    archdaily:'https://www.archdaily.com/tag/british-museum',
    wiki:'https://en.wikipedia.org/wiki/Queen_Elizabeth_II_Great_Court',
    tags:['Foster + Partners','Gridshell','Glass Roof','British Museum','Free','Bloomsbury','Parametric','Reading Room'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/British_Museum_Great_Court_roof.jpg/800px-British_Museum_Great_Court_roof.jpg'
    ],
    drawings:[]
  },

  {
    id:'canary-wharf-station',
    name:'Canary Wharf Underground Station',
    cat:'Infrastructure', cc:'c-inf', styleGroup:'High-Tech',
    era:'1970Ã¢ÂÂ1999', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:1999, access:'Free Admission', style:'High-Tech',
    lat:51.5051, lng:-0.0198,
    addr:'Canary Wharf, Isle of Dogs, London E14 5AB', hood:'Canary Wharf',
    desc:'Foster + Partners\'s Jubilee Line extension station at Canary Wharf is one of the largest underground stations ever built in Britain Ã¢ÂÂ a vast elliptical concrete cavern 300 metres long and 28 metres high, capable of handling 40 trains per hour. The station\'s coffered concrete roof and glass canopy entrance, sheltering commuters like the ribbed shell of a mussel, became an icon of late 1990s infrastructure ambition. It was part of the celebrated Jubilee Line Extension, a project that turned the London Underground into a gallery of contemporary architecture with individual stations designed by Roland Paoletti\'s roster of landmark architects.',
    hours:'MonÃ¢ÂÂSat 5:00 AM Ã¢ÂÂ 12:30 AM ÃÂ· Sun 7:00 AM Ã¢ÂÂ 11:30 PM',
    lastEntry:'',
    admission:'Oyster/contactless or valid ticket required',
    tourOk:false, tourInfo:'The station is a working transport hub. The dramatic concourse and escalator hall are visible to all passengers.',
    web:'https://tfl.gov.uk',
    transit:'Jubilee Ã¢ÂÂ Canary Wharf ÃÂ· Elizabeth line Ã¢ÂÂ Canary Wharf',
    walkFrom:'One Canada Square: 3 min ÃÂ· Museum of London Docklands: 8 min',
    gmaps:'https://maps.google.com/?q=Canary+Wharf+Underground+Station',
    archdaily:'https://www.archdaily.com/tag/canary-wharf-station',
    wiki:'https://en.wikipedia.org/wiki/Canary_Wharf_tube_station',
    tags:['Foster + Partners','Jubilee Line','Infrastructure','Underground','Canary Wharf','Concrete','1999'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Canary_Wharf_tube_station_2012.jpg/800px-Canary_Wharf_tube_station_2012.jpg'
    ],
    drawings:[]
  },

  {
    id:'city-hall-london',
    name:'City Hall (GLA Building)',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2002, access:'Free Admission', style:'Contemporary',
    lat:51.5055, lng:-0.0785,
    addr:'The Queen\'s Walk, Southwark, London SE1 2AA', hood:'South Bank / London Bridge',
    desc:'London\'s City Hall, completed in 2002 on the South Bank opposite the Tower of London, is an exercise in geometric energy efficiency: the building\'s distinctive tilted globe form minimises surface area exposed to direct sunlight, reducing solar gain, while a 500-metre public spiral ramp winds upward through its ten storeys. Foster + Partners calculated the optimal tilt angle to shade the offices below, creating a shape that appears different from every angle. Though the Greater London Authority relocated to Stratford in 2021 and the building was rebranded, it remains a major public space housing the outdoor amphitheatre The Scoop on its riverside.',
    hours:'Exterior and riverside: always open ÃÂ· Interior access varies',
    lastEntry:'',
    admission:'Free (exterior)',
    tourOk:true, tourInfo:'The building is visible from the riverside walk and the interior ramp was historically open during business hours. Check current access with the current operator.',
    web:'https://www.london.gov.uk',
    transit:'Jubilee Ã¢ÂÂ London Bridge (5 min) ÃÂ· Northern Ã¢ÂÂ London Bridge (5 min)',
    walkFrom:'Tower Bridge: 4 min ÃÂ· Tate Modern: 15 min ÃÂ· Borough Market: 8 min',
    gmaps:'https://maps.google.com/?q=City+Hall+London+Queens+Walk',
    archdaily:'https://www.archdaily.com/tag/city-hall-london',
    wiki:'https://en.wikipedia.org/wiki/City_Hall,_London',
    tags:['Foster + Partners','GLA','South Bank','Sustainable','Globe','Spiral Ramp','Thames'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/The_scoop_and_city_hall_2.jpg/800px-The_scoop_and_city_hall_2.jpg'
    ],
    drawings:[]
  },

  {
    id:'millennium-bridge-london',
    name:'Millennium Bridge',
    cat:'Infrastructure', cc:'c-inf', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners', 'Arup', 'Anthony Caro'],
    yr:2002, access:'Free Admission', style:'Contemporary',
    lat:51.5096, lng:-0.0981,
    addr:'Millennium Bridge, City of London / Bankside EC4V 3QH', hood:'City of London / Bankside',
    desc:'London\'s only dedicated pedestrian crossing over the Thames, the Millennium Bridge connects St Paul\'s Cathedral to Tate Modern in a single elegant aluminium span of 325 metres. Designed by Foster + Partners with engineers Arup and sculptor Anthony Caro, the bridge was famously closed two days after opening in 2000 due to unexpected lateral swaying caused by pedestrian footfall synchronisation Ã¢ÂÂ the "wobbly bridge" becoming one of engineering\'s most public failures. Following a ÃÂ£5 million modification to install 37 fluid viscous dampers, it reopened in 2002 and is now one of London\'s most beloved public spaces.',
    hours:'Always open',
    lastEntry:'',
    admission:'Free',
    tourOk:true, tourInfo:'The bridge is a public pedestrian route open at all times. The views of St Paul\'s from the South Bank end are among London\'s finest.',
    web:'https://en.wikipedia.org/wiki/Millennium_Bridge,_London',
    transit:'Central Ã¢ÂÂ St Paul\'s (5 min) ÃÂ· Jubilee Northern Ã¢ÂÂ Southwark (5 min)',
    walkFrom:'St Paul\'s Cathedral: 5 min ÃÂ· Tate Modern: 3 min ÃÂ· Shakespeare\'s Globe: 7 min',
    gmaps:'https://maps.google.com/?q=Millennium+Bridge+London',
    archdaily:'https://www.archdaily.com/tag/millennium-bridge',
    wiki:'https://en.wikipedia.org/wiki/Millennium_Bridge,_London',
    tags:['Foster + Partners','Arup','Bridge','Pedestrian','Thames','Millennium','Wobbly Bridge','Free','St Paul\'s'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Millennium_Bridge_from_Tate_Modern.jpg/800px-Millennium_Bridge_from_Tate_Modern.jpg'
    ],
    drawings:[]
  },

  {
    id:'hsbc-8-canada-square',
    name:'HSBC UK HQ (8 Canada Square)',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'High-Tech',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners'],
    yr:2002, access:'Private', style:'High-Tech',
    lat:51.5041, lng:-0.0202,
    addr:'8 Canada Square, Canary Wharf, London E14 5HQ', hood:'Canary Wharf',
    desc:'The HSBC Group headquarters at 8 Canada Square is one of the defining towers of Canary Wharf\'s second generation, a 200-metre steel-and-glass prism completed by Foster + Partners in 2002. Unlike the ornamental pyramid of One Canada Square nearby, HSBC\'s tower is rigorously technical Ã¢ÂÂ its structural frame is fully expressed on the exterior, the facade flush and precisely detailed, the plan a pure 57ÃÂ57-metre square. The building\'s mechanical plant, staircases and lifts are distributed on the perimeter, freeing all 50,000 square metres of floor space from internal obstructions, and the trading floors were among the most advanced in the world at opening.',
    hours:'Private Ã¢ÂÂ no public access',
    lastEntry:'',
    admission:'Private (office building)',
    tourOk:false, tourInfo:'The building is closed to the public. The Canary Wharf estate and its public spaces surrounding the tower are accessible to all.',
    web:'https://www.canarywharf.com',
    transit:'Jubilee Ã¢ÂÂ Canary Wharf ÃÂ· Elizabeth line Ã¢ÂÂ Canary Wharf (3 min)',
    walkFrom:'Canary Wharf Station: 3 min ÃÂ· One Canada Square: 5 min ÃÂ· Museum of London Docklands: 8 min',
    gmaps:'https://maps.google.com/?q=8+Canada+Square+Canary+Wharf',
    archdaily:'https://www.archdaily.com/tag/hsbc-canary-wharf',
    wiki:'https://en.wikipedia.org/wiki/HSBC_UK_Building,_London',
    tags:['Foster + Partners','HSBC','Canary Wharf','Skyscraper','High-Tech','Office','Docklands'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/8_Canada_Square.jpg/800px-8_Canada_Square.jpg'
    ],
    drawings:[]
  },

  {
    id:'wembley-stadium',
    name:'Wembley Stadium',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Foster + Partners', archs:['Foster + Partners', 'HOK Sport'],
    yr:2007, access:'Paid Ticket', style:'Contemporary',
    lat:51.5560, lng:-0.2796,
    addr:'Olympic Way, Wembley, London HA9 0WS', hood:'Wembley',
    desc:'The new Wembley Stadium, designed by Foster + Partners and HOK Sport and opened in 2007, is England\'s national football ground and Europe\'s second-largest stadium at 90,000 capacity. Its defining feature is the 133-metre-high steel arch that spans the entire length of the pitch, supporting the vast retractable roof and serving as a landmark visible from much of London. The arch replaced the Twin Towers of the original 1923 Wembley, which had become synonymous with English football but were structurally inadequate. The roof covers all 90,000 seats Ã¢ÂÂ a first for a stadium of this scale Ã¢ÂÂ and the arch doubles as a navigation beacon for Heathrow flights.',
    hours:'Tours: Daily 10:00 AM Ã¢ÂÂ 4:00 PM (non-event days) ÃÂ· Events: varies',
    lastEntry:'',
    admission:'Stadium tours: ÃÂ£25 adults ÃÂ· Match tickets vary',
    tourOk:true, tourInfo:'Behind-the-scenes stadium tours run daily on non-event days, including access to changing rooms, players\' tunnel, and the pitch-side view.',
    web:'https://www.wembleystadium.com',
    transit:'Metropolitan Ã¢ÂÂ Wembley Park (10 min walk) ÃÂ· Jubilee Ã¢ÂÂ Wembley Park',
    walkFrom:'Wembley Park Station: 10 min ÃÂ· Wembley Arena: 8 min',
    gmaps:'https://maps.google.com/?q=Wembley+Stadium',
    archdaily:'https://www.archdaily.com/tag/wembley-stadium',
    wiki:'https://en.wikipedia.org/wiki/Wembley_Stadium',
    tags:['Foster + Partners','HOK Sport','Stadium','Arch','Football','National Stadium','Wembley'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Wembley_Stadium_-_May_2011.jpg/800px-Wembley_Stadium_-_May_2011.jpg'
    ],
    drawings:[]
  },

  // Ã¢ÂÂÃ¢ÂÂ RICHARD ROGERS / ROGERS STIRK HARBOUR + PARTNERS Ã¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂ

  {
    id:'lloyds-of-london',
    name:"Lloyd's of London",
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'High-Tech',
    era:'1970Ã¢ÂÂ1999', city:'london',
    arch:'Richard Rogers Partnership', archs:['Richard Rogers Partnership'],
    yr:1986, access:'Private', style:'High-Tech',
    lat:51.5127, lng:-0.0825,
    addr:'1 Lime Street, City of London EC3M 7HA', hood:'City of London',
    desc:'Lloyd\'s of London is the building that defined the High-Tech architectural movement and made Richard Rogers a global name. Completed in 1986, six years after the Centre Pompidou in Paris established the style Rogers co-invented with Renzo Piano, Lloyd\'s turned the principle inside out on a tight City of London plot: all service elements Ã¢ÂÂ lifts, staircases, utilities, lavatories Ã¢ÂÂ are externalised into six satellite towers on the perimeter, liberating the interior for the vast open trading floor known as the "Room." The building\'s stainless steel ducts, blue crane arms and exposed structure are simultaneously industrial and elegant, and it remains the most radical corporate building ever erected in the City.',
    hours:'Private Ã¢ÂÂ no public access',
    lastEntry:'',
    admission:'Private (working insurance market)',
    tourOk:false, tourInfo:'The building is a working insurance market and not open to the public. Open House London sometimes grants access. The exterior is best viewed from Lime Street.',
    web:'https://www.lloyds.com',
    transit:'Circle District Hammersmith Ã¢ÂÂ Monument (5 min) ÃÂ· Central Ã¢ÂÂ Bank (5 min)',
    walkFrom:'Leadenhall Market: 3 min ÃÂ· Gherkin: 3 min ÃÂ· Bank: 8 min',
    gmaps:'https://maps.google.com/?q=Lloyd%27s+of+London',
    archdaily:'https://www.archdaily.com/tag/lloyds-of-london',
    wiki:"https://en.wikipedia.org/wiki/Lloyd%27s_of_London_(building)",
    tags:['Richard Rogers','High-Tech','Inside-Out','Insurance','City of London','Grade I Listed','1986','Stainless Steel'],
    photos:[
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Lloyds_of_london_2012.jpg/800px-Lloyds_of_london_2012.jpg"
    ],
    drawings:[]
  },

  {
    id:'leadenhall-building',
    name:'Leadenhall Building (Cheesegrater)',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'High-Tech',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Rogers Stirk Harbour + Partners', archs:['Rogers Stirk Harbour + Partners'],
    yr:2014, access:'Free Admission', style:'High-Tech',
    lat:51.5138, lng:-0.0826,
    addr:'122 Leadenhall Street, City of London EC3V 4AB', hood:'City of London',
    desc:'The Leadenhall Building Ã¢ÂÂ popularly the "Cheesegrater" for its wedge-shaped profile Ã¢ÂÂ tapers northward to preserve the protected view of St Paul\'s Cathedral from Fleet Street, transforming a planning constraint into its most distinctive architectural feature. Rogers Stirk Harbour + Partners\'s 224-metre tower, completed in 2014, expresses its megaframe structural system entirely on the exterior in orange-painted steel, freeing the 48,000-square-metre interior of every column. A 15-storey public atrium at the base extends the City\'s streets into the building at ground level, a rare act of civic generosity in London\'s financial district.',
    hours:'Public atrium: MonÃ¢ÂÂFri 7:00 AM Ã¢ÂÂ 7:00 PM ÃÂ· Office floors: private',
    lastEntry:'',
    admission:'Free (ground floor atrium)',
    tourOk:true, tourInfo:'The public atrium with its dramatic exposed steel frame is open during business hours. Sky garden access is private.',
    web:'https://www.theleadenhallbuilding.com',
    transit:'Circle District Ã¢ÂÂ Aldgate (5 min) ÃÂ· Central Waterloo & City Ã¢ÂÂ Bank (7 min)',
    walkFrom:'Lloyd\'s of London: 1 min ÃÂ· Gherkin: 3 min ÃÂ· Leadenhall Market: 2 min',
    gmaps:'https://maps.google.com/?q=Leadenhall+Building+London',
    archdaily:'https://www.archdaily.com/tag/leadenhall-building',
    wiki:'https://en.wikipedia.org/wiki/Leadenhall_Building',
    tags:['Rogers Stirk Harbour + Partners','Richard Rogers','Cheesegrater','Skyscraper','High-Tech','Megaframe','City of London','St Paul\'s View'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Leadenhall_Building_from_Gracechurch_Street_2014.jpg/800px-Leadenhall_Building_from_Gracechurch_Street_2014.jpg'
    ],
    drawings:[]
  },

  {
    id:'o2-arena',
    name:'The O2 Arena (Millennium Dome)',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'High-Tech',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Richard Rogers Partnership', archs:['Richard Rogers Partnership', 'Buro Happold'],
    yr:2000, access:'Paid Ticket', style:'High-Tech',
    lat:51.5030, lng:0.0032,
    addr:'Peninsula Square, Greenwich, London SE10 0DX', hood:'Greenwich Peninsula',
    desc:'The Millennium Dome Ã¢ÂÂ now The O2 Ã¢ÂÂ is the world\'s largest dome structure, a 365-metre diameter tensile fabric roof supported by twelve 100-metre steel masts whose number evokes the months of the year and the hours on a clock face. Designed by Richard Rogers Partnership with Buro Happold as a national monument for the millennium, it opened on 31 December 1999 and was immediately controversial; following closure in 2001, AEG transformed it into The O2, Europe\'s busiest entertainment arena. The dome\'s fabric roof is now traversable on a guided "Up at The O2" climbing experience.',
    hours:'Entertainment venue: event days only ÃÂ· Up at The O2: daily 10:00 AM Ã¢ÂÂ 5:00 PM',
    lastEntry:'',
    admission:'Entry to The O2 varies by event ÃÂ· Up at The O2: from ÃÂ£30',
    tourOk:true, tourInfo:'The Up at The O2 roof walk is open daily and provides panoramic views of London. The entertainment complex is accessible to the public.',
    web:'https://www.theo2.co.uk',
    transit:'Jubilee Ã¢ÂÂ North Greenwich (adjacent)',
    walkFrom:'North Greenwich Station: 5 min',
    gmaps:'https://maps.google.com/?q=The+O2+Arena+London',
    archdaily:'https://www.archdaily.com/tag/millennium-dome',
    wiki:'https://en.wikipedia.org/wiki/The_O2_Arena',
    tags:['Richard Rogers','Millennium Dome','O2','Tensile Structure','High-Tech','Greenwich','Masts','Entertainment'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/The_O2%2C_London_2012.jpg/800px-The_O2%2C_London_2012.jpg'
    ],
    drawings:[]
  },

  {
    id:'heathrow-terminal-5',
    name:'Heathrow Terminal 5',
    cat:'Infrastructure', cc:'c-inf', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Rogers Stirk Harbour + Partners', archs:['Rogers Stirk Harbour + Partners'],
    yr:2008, access:'Paid Ticket', style:'Contemporary',
    lat:51.4721, lng:-0.4877,
    addr:'Heathrow Airport, Terminal 5, Longford, Hounslow TW6 2GA', hood:'Heathrow',
    desc:'Heathrow Terminal 5 is one of the largest buildings in the United Kingdom, a single-span roof 396 metres long covering a naturally lit concourse designed to handle 30 million passengers a year. Rogers Stirk Harbour + Partners\'s design, developed over 19 years through one of the longest planning inquiries in British history, uses 16 roof "petals" Ã¢ÂÂ prefabricated off-site Ã¢ÂÂ that click together to form a gentle wave above the passenger hall. The terminal\'s structural system is deliberately exposed, creating a light-filled space that counters the typical enclosure of airport terminals, and the primary structure required no paint or fire protection due to innovative engineering.',
    hours:'24 hours (operational)',
    lastEntry:'',
    admission:'Access for passengers with valid tickets only',
    tourOk:false, tourInfo:'Terminal 5 is restricted to departing passengers and those with arriving passengers. The building\'s most dramatic spaces Ã¢ÂÂ the departure hall and its roof Ã¢ÂÂ are visible only from airside.',
    web:'https://www.heathrow.com/terminals/terminal-5',
    transit:'Elizabeth line Ã¢ÂÂ Heathrow Terminal 5 (direct) ÃÂ· Heathrow Express Ã¢ÂÂ Paddington (21 min)',
    walkFrom:'Terminal 5 Station: adjacent',
    gmaps:'https://maps.google.com/?q=Heathrow+Terminal+5',
    archdaily:'https://www.archdaily.com/tag/heathrow-terminal-5',
    wiki:'https://en.wikipedia.org/wiki/Heathrow_Terminal_5',
    tags:['Rogers Stirk Harbour + Partners','Richard Rogers','Heathrow','Airport','Infrastructure','Single Span Roof','Terminal'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/T5A_interior.jpg/800px-T5A_interior.jpg'
    ],
    drawings:[]
  },

  {
    id:'one-hyde-park',
    name:'One Hyde Park',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Rogers Stirk Harbour + Partners', archs:['Rogers Stirk Harbour + Partners'],
    yr:2011, access:'Private', style:'Contemporary',
    lat:51.5023, lng:-0.1603,
    addr:'Knightsbridge, London SW1X 7LJ', hood:'Knightsbridge',
    desc:'One Hyde Park is the world\'s most expensive residential development, its four glass pavilions rising adjacent to Hyde Park at Knightsbridge and regularly cited as London\'s priciest address. Rogers Stirk Harbour + Partners designed the development as a series of four linked but separate residential blocks, each rotated to maximise park views, with shared leisure facilities including a swimming pool, spa, cinema and squash courts concealed below ground. At opening, its penthouse apartments sold for over ÃÂ£100 million each. The building\'s transparent glass facades were a deliberate counterpoint to the closed, defensive architecture typical of ultra-luxury London developments.',
    hours:'Private residential Ã¢ÂÂ no public access',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'One Hyde Park is a private residential development. The adjacent Hyde Park and the Serpentine Gallery are open to the public.',
    web:'https://www.onehydepark.com',
    transit:'Piccadilly Ã¢ÂÂ Knightsbridge (3 min)',
    walkFrom:'Hyde Park: 1 min ÃÂ· Harrods: 5 min ÃÂ· Serpentine Gallery: 10 min',
    gmaps:'https://maps.google.com/?q=One+Hyde+Park+London',
    archdaily:'https://www.archdaily.com/tag/one-hyde-park',
    wiki:'https://en.wikipedia.org/wiki/One_Hyde_Park',
    tags:['Rogers Stirk Harbour + Partners','Richard Rogers','Luxury Residential','Knightsbridge','Hyde Park','World\'s Most Expensive'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/One_Hyde_Park_from_Knightsbridge.jpg/800px-One_Hyde_Park_from_Knightsbridge.jpg'
    ],
    drawings:[]
  },

  {
    id:'88-wood-street',
    name:'88 Wood Street',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'High-Tech',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Rogers Stirk Harbour + Partners', archs:['Rogers Stirk Harbour + Partners'],
    yr:2000, access:'Private', style:'High-Tech',
    lat:51.5158, lng:-0.0912,
    addr:'88 Wood Street, City of London EC2V 7RS', hood:'City of London',
    desc:'88 Wood Street is among Richard Rogers\'s most sophisticated smaller towers, a 19-storey office building in the heart of the City whose facade changes expression across its four elevations to respond to the surrounding streets. The north face is enclosed in reflective glass, while the south is opened up with projecting aluminium sunshades; the east and west elevations express the building\'s structural frame. Most distinctive is the cylindrical utility tower that breaks free of the rectangular mass at the north-east corner Ã¢ÂÂ a characteristically Rogers move that externalises services into an architectural element and creates variety in the City\'s streetscape.',
    hours:'Private office building',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'The building is a private office building. The exterior is fully viewable from Wood Street and Fore Street.',
    web:'https://www.rshp.com',
    transit:'Central Ã¢ÂÂ St Paul\'s (5 min) ÃÂ· Metropolitan Circle District Ã¢ÂÂ Barbican (5 min)',
    walkFrom:'Barbican: 7 min ÃÂ· St Paul\'s: 7 min ÃÂ· Museum of London: 5 min',
    gmaps:'https://maps.google.com/?q=88+Wood+Street+London',
    archdaily:'https://www.archdaily.com/tag/88-wood-street',
    wiki:'https://en.wikipedia.org/wiki/88_Wood_Street',
    tags:['Rogers Stirk Harbour + Partners','Richard Rogers','High-Tech','City of London','Office','Cylindrical Tower'],
    photos:[],
    drawings:[]
  },

  {
    id:'neo-bankside',
    name:'Neo Bankside',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Rogers Stirk Harbour + Partners', archs:['Rogers Stirk Harbour + Partners'],
    yr:2012, access:'Private', style:'Contemporary',
    lat:51.5072, lng:-0.1012,
    addr:'Holland Street, Bankside, London SE1 9JU', hood:'Bankside / Southwark',
    desc:'Neo Bankside is a luxury residential development of six pavilions on London\'s South Bank, directly adjacent to Tate Modern, that became the centre of a significant privacy dispute when Tate Modern\'s Blavatnik Building extension opened its viewing terrace overlooking the apartments\' floor-to-ceiling glazed facades. Rogers Stirk Harbour + Partners deliberately used transparent glass as an ethical stance Ã¢ÂÂ the architects believed Londoners had a right to live openly in the city Ã¢ÂÂ but the dispute, which reached the UK Supreme Court, highlighted the tensions between architectural transparency and residential privacy. The development\'s expressed steel frames and richly coloured service cores are characteristic of Rogers\'s palette.',
    hours:'Private residential',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'Neo Bankside is private. The adjacent Tate Modern, Shakespeare\'s Globe, and Bankside riverside walk are all public.',
    web:'https://www.rshp.com',
    transit:'Jubilee Northern Ã¢ÂÂ Southwark (7 min) ÃÂ· District Circle Ã¢ÂÂ Blackfriars (8 min)',
    walkFrom:'Tate Modern: 2 min ÃÂ· Shakespeare\'s Globe: 4 min ÃÂ· Millennium Bridge: 5 min',
    gmaps:'https://maps.google.com/?q=Neo+Bankside+London',
    archdaily:'https://www.archdaily.com/tag/neo-bankside',
    wiki:'https://en.wikipedia.org/wiki/Neo_Bankside',
    tags:['Rogers Stirk Harbour + Partners','Richard Rogers','Residential','Bankside','South Bank','Transparency','Tate Modern'],
    photos:[],
    drawings:[]
  },

  {
    id:'montevetro',
    name:'Montevetro',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'1970Ã¢ÂÂ1999', city:'london',
    arch:'Richard Rogers Partnership', archs:['Richard Rogers Partnership'],
    yr:1999, access:'Private', style:'Contemporary',
    lat:51.4731, lng:-0.1723,
    addr:'Battersea Church Road, Battersea, London SW11 3LY', hood:'Battersea',
    desc:'Montevetro is Richard Rogers\'s first major residential tower in London, a tapering glass block of 103 apartments rising above the Thames at Battersea that pioneered the transparent, light-filled residential aesthetic Rogers would later develop at Neo Bankside. Completed in 1999 on the site of a former flour mill, the building\'s glass facade steps back in plan at each floor to follow the building\'s triangular site, creating a distinctive silhouette when viewed from the river. The project helped establish Battersea\'s transformation from industrial riverside district to luxury residential neighbourhood, a process that continues with the adjacent Battersea Power Station redevelopment.',
    hours:'Private residential',
    lastEntry:'',
    admission:'Private',
    tourOk:false, tourInfo:'The building is private residential. The Thames Path alongside provides good views of the facade from the riverside.',
    web:'https://www.rshp.com',
    transit:'Overground Ã¢ÂÂ Clapham Junction (15 min walk) ÃÂ· Bus 344 Ã¢ÂÂ Battersea Church Road',
    walkFrom:'Battersea Power Station: 12 min ÃÂ· Chelsea Bridge: 10 min',
    gmaps:'https://maps.google.com/?q=Montevetro+Battersea+London',
    archdaily:'https://www.archdaily.com/tag/montevetro',
    wiki:'https://en.wikipedia.org/wiki/Montevetro',
    tags:['Richard Rogers','Residential','Battersea','Thames','Glass','1999'],
    photos:[],
    drawings:[]
  },

  {
    id:'chiswick-business-park',
    name:'Chiswick Business Park',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Richard Rogers Partnership', archs:['Richard Rogers Partnership'],
    yr:2000, access:'Free Admission', style:'Contemporary',
    lat:51.4913, lng:-0.2652,
    addr:'566 Chiswick High Road, Chiswick, London W4 5YE', hood:'Chiswick',
    desc:'Chiswick Business Park is Rogers\'s largest commercial campus in London, a landscaped park of twelve office buildings arranged around a central lake and public gardens in west London, developed by Stanhope from 2000 onwards. Unlike conventional business parks designed for car dependency, Chiswick was conceived as a community Ã¢ÂÂ a "campus" with cafes, concierge services, and a hotel integrated into the landscape Ã¢ÂÂ that anticipated the post-industrial workplace. The buildings\' expressed steel structures and coloured panel systems are characteristic of Rogers\'s vocabulary, and the public lake and gardens are open to all, making it one of west London\'s more pleasant semi-public green spaces.',
    hours:'Public gardens and lake: daily dawn to dusk ÃÂ· Offices: private',
    lastEntry:'',
    admission:'Free (public grounds)',
    tourOk:true, tourInfo:'The public gardens, lake and outdoor seating areas are accessible to all. Individual buildings are private offices.',
    web:'https://www.chiswickpark.com',
    transit:'District Ã¢ÂÂ Gunnersbury or Chiswick Park (10Ã¢ÂÂ15 min walk)',
    walkFrom:'Gunnersbury Station: 12 min ÃÂ· Kew Bridge: 15 min',
    gmaps:'https://maps.google.com/?q=Chiswick+Business+Park+London',
    archdaily:'https://www.archdaily.com/tag/chiswick-business-park',
    wiki:'https://en.wikipedia.org/wiki/Chiswick_Business_Park',
    tags:['Richard Rogers','Business Park','Chiswick','Campus','Landscape','Lake','West London'],
    photos:[],
    drawings:[]
  },

  // Ã¢ÂÂÃ¢ÂÂ RENZO PIANO Ã¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂÃ¢ÂÂ

  {
    id:'the-shard',
    name:'The Shard',
    cat:'Skyscrapers', cc:'c-sky', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Renzo Piano Building Workshop', archs:['Renzo Piano Building Workshop'],
    yr:2012, access:'Paid Ticket', style:'Contemporary',
    lat:51.5045, lng:-0.0865,
    addr:'32 London Bridge Street, London SE1 9SG', hood:'London Bridge / Southwark',
    desc:'At 310 metres, the Shard is Western Europe\'s tallest building, its tapering glass spire rising above London Bridge to become the South Bank\'s defining landmark. Renzo Piano\'s design draws on the vertical spires of Wren\'s City churches and the masts of the Thames sailing ships visible in 18th-century paintings of the river Ã¢ÂÂ the concept of a "shard of glass" inserted into London\'s skyline. The building\'s eight angled glass facades are designed to never appear the same twice: the glass is slightly angled at each floor so they reflect different parts of the sky throughout the day and in different weathers. Inside, a mixed-use vertical city combines offices, hotel, apartments, restaurants, and a public viewing gallery at levels 68Ã¢ÂÂ72.',
    hours:'Viewing Gallery: daily 10:00 AM Ã¢ÂÂ 10:00 PM (FriÃ¢ÂÂSat to 11:00 PM)',
    lastEntry:'1 hour before closing',
    admission:'Viewing Gallery: from ÃÂ£32 adults ÃÂ· Combined tickets available',
    tourOk:true, tourInfo:'The View from The Shard on levels 68Ã¢ÂÂ72 is open to the public. The Sky Deck at level 72 is open-air. Booking in advance strongly recommended.',
    web:'https://www.theviewfromtheshard.com',
    transit:'Jubilee Northern Ã¢ÂÂ London Bridge (adjacent)',
    walkFrom:'London Bridge Station: 2 min ÃÂ· Borough Market: 4 min ÃÂ· Tate Modern: 12 min',
    gmaps:'https://maps.google.com/?q=The+Shard+London',
    archdaily:'https://www.archdaily.com/tag/the-shard',
    wiki:'https://en.wikipedia.org/wiki/The_Shard',
    tags:['Renzo Piano','Shard','Skyscraper','Western Europe Tallest','London Bridge','Viewing Gallery','Mixed Use'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/The_Shard_from_the_Sky_Garden.jpg/800px-The_Shard_from_the_Sky_Garden.jpg'
    ],
    drawings:[]
  },

  {
    id:'central-st-giles',
    name:'Central Saint Giles',
    cat:'Modern Architecture', cc:'c-mod', styleGroup:'Contemporary',
    era:'2000Ã¢ÂÂPresent', city:'london',
    arch:'Renzo Piano Building Workshop', archs:['Renzo Piano Building Workshop'],
    yr:2010, access:'Free Admission', style:'Contemporary',
    lat:51.5163, lng:-0.1234,
    addr:'1 St Giles High Street, London WC2H 8AG', hood:'Covent Garden / Soho',
    desc:'Central Saint Giles is Renzo Piano\'s most colourful work in London, its facade of glazed ceramic tiles in acid yellow, lime green and orange creating a vivid counterpoint to the grey brick of the surrounding West End streets. Developed on the site of a former Home Office building and completed in 2010, the mixed-use complex houses offices and apartments around a publicly accessible central courtyard. Piano\'s use of bold colour to define urban space was deliberate: the building acts as a wayfinding marker in the complex street grid between Soho, Covent Garden and Bloomsbury, and the ceramic tiles were chosen to remain bright and self-cleaning in London\'s rain.',
    hours:'Public courtyard: daily ÃÂ· Offices: private',
    lastEntry:'',
    admission:'Free (public courtyard)',
    tourOk:true, tourInfo:'The public courtyard is open to all. The coloured facades are best seen from the central courtyard or from Monmouth Street.',
    web:'https://www.centralstgiles.com',
    transit:'Central Northern Piccadilly Ã¢ÂÂ Tottenham Court Road (3 min)',
    walkFrom:'Tottenham Court Road: 3 min ÃÂ· Covent Garden: 7 min ÃÂ· Soho: 5 min ÃÂ· British Museum: 8 min',
    gmaps:'https://maps.google.com/?q=Central+Saint+Giles+London',
    archdaily:'https://www.archdaily.com/tag/central-saint-giles',
    wiki:'https://en.wikipedia.org/wiki/Central_Saint_Giles',
    tags:['Renzo Piano','Ceramic Tiles','Coloured Facade','Covent Garden','Mixed Use','West End','Free','Courtyard'],
    photos:[
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Central_Saint_Giles%2C_London.jpg/800px-Central_Saint_Giles%2C_London.jpg'
    ],
    drawings:[]
  }
,
  {
    id: 'va-east-storehouse',
    name: 'V&A East Storehouse',
    cat: 'Museums & Culture',
    cc: 'c-mus',
    styleGroup: 'Contemporary',
    era: '2000–Present',
    city: 'london',
    arch: 'Diller Scofidio + Renfro',
    archs: ['Diller Scofidio + Renfro'],
    yr: 2025,
    access: 'Free Admission',
    style: 'Contemporary',
    lat: 51.5508,
    lng: -0.0127,
    addr: 'Here East, Queen Elizabeth Olympic Park, London E20 3BS',
    hood: 'Stratford / Olympic Park',
    desc: "V&A East Storehouse is a major new museum building by Diller Scofidio + Renfro, forming part of the V&A's landmark expansion into east London. Located within the former Olympic broadcast centre at Here East, the building preserves and reveals the industrial heritage of the site while creating vast open gallery spaces that display approximately 250,000 objects from the V&A's collection in a visible storage model. Opened in May 2025, it democratises access to items rarely seen in traditional museum settings.",
    hours: 'Wed–Sun 10am–6pm',
    lastEntry: '5:30pm',
    admission: 'Free',
    tourOk: true,
    tourInfo: 'Free entry. Group tours and community programmes available.',
    web: 'https://www.vam.ac.uk/east',
    transit: 'Elizabeth line / Central / Jubilee / DLR — Stratford',
    walkFrom: 'Stratford International: 10 min · Olympic Park: 5 min',
    gmaps: 'https://maps.google.com/?q=V%26A+East+Storehouse+London',
    archdaily: 'https://www.archdaily.com/tag/v-and-a-east',
    wiki: 'https://en.wikipedia.org/wiki/V%26A_East',
    tags: ['Diller Scofidio + Renfro', 'Museum', 'Visible Storage', 'Olympic Park', 'Industrial Conversion', 'East London'],
    photos: [],
    drawings: []
  }
];
/* DATA_END */
